### ISSUE TITLE
Not able to connect to GKE clusters

### ISSUE THREAD

**Issue by jsmichaels** [harbur/kubernetic#105]
We have several clusters, both on-prem and GKE, and there's no issue accessing them via `kubectl`. Kubernetic also doesn't have any trouble with our on-prem clusters, but GKE clusters perpetually have the red dot next to the cluster name, and no information appears in the UI. This issue appeared several months ago all of a sudden; Kubernetic used to be able to load GKE clusters just fine.

**Comment by spiddy** [comment]
released 2.4.0 which fixes connectivity to GKE
