### ISSUE TITLE
Unable to connect to rancher/k3s cluster

### ISSUE THREAD

**Issue by yp28** [harbur/kubernetic#106]
kubectl version: `v1.13.0`
[rancher/k3s](https://github.com/rancher/k3s) version: `v1.14.1-k3s.4`
kubernetic version: `2.3.0`

Possibly linked to #105 due to the unconventional kube-master setup. On GKE it is run by Google Cloud Platform, k3s is an all in one solution where a binary runs (almost) all Kubernetes core components.

Edit: added kubernetic version

**Comment by spiddy** [comment]
released Kubernetic 2.4.0 which is now tested also against k3s and works ok.

Note that the process of k3s kubeconfig generation is to prepare a separate kubeconfig file and point there, you need add the kube configuration to the `~/.kube/config` file so that Kubernetic picks it up.
