### ISSUE TITLE
[Feature Request] Show allocated resources (requests and limits) per node

### ISSUE THREAD

**Issue by centurytech** [harbur/kubernetic#107]
The Kubernetes dashboard currently shows allocated resources like cores, memory or pods as both requests and limits per node (see picture). We are using this a lot for capacity planning etc. I'd love to see this added to Kubernetic.

<img width="1367" alt="cpu_memory" src="https://user-images.githubusercontent.com/15195362/64264059-bd769580-cf41-11e9-90eb-39b407f40e89.png">

**Comment by dkapanidis** [comment]
Nodes metrics have been added, they are retrieved from the kubernetes API, same way as the `kubectl describe node` collects the node resources.

<img width="1099" alt="Screenshot 2020-05-26 at 14 29 12" src="https://user-images.githubusercontent.com/367397/82900754-4bc1fa00-9f5d-11ea-92f3-043740189312.png">

<img width="1108" alt="Screenshot 2020-05-26 at 14 31 19" src="https://user-images.githubusercontent.com/367397/82900990-98a5d080-9f5d-11ea-82ad-3849f0ac7428.png">
