### ISSUE TITLE
[Feature Request] Support for custom resources (kind)

### ISSUE THREAD

**Issue by foal** [harbur/kubernetic#108]
For example, edit and manage the certmanager cluster issuers (kind: ClusterIssuer)

**Comment by shiipou** [comment]
+1

Need to show and edit Custom resources like for traefik IngressRoute and IngressRouteTCP
This allow to change out of the cli the configuration of the reverse-proxy that filter and redirect request to the right container.

Thanks for your good job.

**Comment by dkapanidis** [comment]
dup of #81

**Comment by dkapanidis** [comment]
CRDs are available on 2.7.0:

<img width="1272" alt="Screenshot 2020-05-19 at 12 22 49" src="https://user-images.githubusercontent.com/367397/82315371-7e06b100-99cb-11ea-827f-0f940b540cc7.png">

Note that at the moment only namespaced CRDs are visible, on next release the global CRDs will also be available.
