### ISSUE TITLE
[Feature Request] Support for rollout command

### ISSUE THREAD

**Issue by soderluk** [harbur/kubernetic#109]
The `kubectl rollout restart deployment <name>` is pretty useful when you need to restart a failing deployment.

A nice feature would be to support the `kubectl rollout` commands.

**Comment by fbjorn** [comment]
👍 would be useful

**Comment by dkapanidis** [comment]
done, will be added on next release v2.7.0:

![rollout](https://user-images.githubusercontent.com/367397/81830434-554e6980-953c-11ea-8e41-4c7f8bd12d3a.gif)
