### ISSUE TITLE
中国大陆地区无法访问官网

### ISSUE THREAD

**Issue by koy1619** [harbur/kubernetic#111]
可否增加国内官网节点

**Comment by tonychee7000** [comment]
还是搭梯子来得实在

**Comment by dkapanidis** [comment]
Tested both the landing page and download domain:
* https://kubernetic.com
* https://kubernetic.s3.amazonaws.com/

using the following tool: https://www.comparitech.com/privacy-security-tools/blockedinchina/
both domains seem to  be ok.

I'll be closing this for now, if there are still issues with connectivity please reopen the issue and we'll investigate further.
