### ISSUE TITLE
[Feature request] Configurable display settings

### ISSUE THREAD

**Issue by dkijkuit** [harbur/kubernetic#112]
It would be nice to be able to show/hide columns in a view. For example, in the pods view I really like to know on which node a pod is running. The information is available, but not shown. Many table oriented views offer this functionality. For example:

![image](https://user-images.githubusercontent.com/16475465/65812654-26140380-e1ca-11e9-9c92-106386c718d9.png)

**Comment by dkapanidis** [comment]
Dynamic tables with customizable columns Implemented on `v3.0.0`

Each resource type displays resource-specific columns as shown in `kubectl`, supporting also CRDs. It displays by default the columns shown using kubectl with the option to display extra columns (that can be enabled in CLI with `kubectl -o wide`).

<img width="1104" alt="Screenshot 2020-11-10 at 14 27 38" src="https://user-images.githubusercontent.com/367397/98679905-f342b580-2360-11eb-98a7-5d2443c83395.png">

<img width="1106" alt="Screenshot 2020-11-10 at 14 28 25" src="https://user-images.githubusercontent.com/367397/98679958-05bcef00-2361-11eb-8a9f-d6bb6921b73f.png">
