### ISSUE TITLE
kubernetic 2.3.0 can't view deployments on kubelet 1.16

### ISSUE THREAD

**Issue by abetan** [harbur/kubernetic#113]
my kubernetic can't view deployments on my cluster (kubelet 1.16). I've read kubernetes doc that since kubelet 1.6, DaemonSet, Deployment, StatefulSet, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 (https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/). Is this the cause why i can't view deployments resource ?

![image](https://user-images.githubusercontent.com/52186378/65931682-fc124980-e434-11e9-8a17-7fa1ccbeef61.png)

**Comment by foal** [comment]
Have the same issue. From all my controllers, I see only one Stateful Set.

**Comment by spiddy** [comment]
Managed to reproduce the issue with minikube v1.4.0 (kubelet v1.16.0), will be resolved on next release.

**Comment by abetan** [comment]
> 
> 
> Managed to reproduce the issue with minikube v1.4.0 (kubelet v1.16.0), will be resolved on next release.

Thanx for your support...:)

**Comment by spiddy** [comment]
New version (2.4.0) is released with the fix

**Comment by abetan** [comment]
Awesome, thanx...
