### ISSUE TITLE
Deployment/replicaset status displays incorrectly when source registry specifies a port number

### ISSUE THREAD

**Issue by dddicillo** [harbur/kubernetic#114]
I may be incorrect in my assumption, but it seems as though the status column in the list of deployments is expected to display the tag of the default image deployed in the pod managed by the associated deployment or replica set. This functionality appears to break when the registry hosting the target image contains a port number in its URL. For example, a deployment which pulls an image from `my.docker.registry:7000/hello-world:1.0.0` will display `7000/hello-world` in the status column upon successful initialization of the pod. I believe the expected functionality is for `1.0.0` to be displayed, similar to the images in the docs: https://docs.kubernetic.com/controllers/4.3.-deployments

**Comment by spiddy** [comment]
Nice catch! You're correct, the code assumes that the `:` only exists once in the string and uses that as separator and shows 2nd entry, thus the output `7000/hello-world`.

Will fix it for the next release so that it's displayed properly

**Comment by spiddy** [comment]
fixed, will be included on next release

**Comment by dddicillo** [comment]
Awesome! Impressive response time too. Cheers!
