### ISSUE TITLE
[Feature request] Helm 3 support

### ISSUE THREAD

**Issue by vaivanov** [harbur/kubernetic#121]
Hello, guys!

Nice project. Are you planning to implement new version of Helm? https://github.com/helm/helm/releases/tag/v3.0.0

Best regards,
Vladimir Ivanov

**Comment by spiddy** [comment]
Yes, that's the plan now that the stable helm v3 is out.

It will be implemented soon, I'll post update here when it's ready.

**Comment by tomerliberman** [comment]
@dkapanidis any updates on this?

**Comment by dkapanidis** [comment]
Helm 3 is now embedded in Kubernetes and supported out-of-the-box. (Helm 2 support has been removed)

Kubernetic version 2.8.0 is bundled with helm v3.2.1.

* Repositories can be managed (create, delete)
* Charts can be browsed (README & Values)
* Releases can be managed (create, upgrade, rollback, delete)
* Releases can be browsed (manifests, notes, values, history) 
* Resources generated by Releases now have a backlink to the Release for discoverability

<img width="1109" alt="Screenshot 2020-06-03 at 15 18 15" src="https://user-images.githubusercontent.com/367397/83641618-109f7680-a5ae-11ea-8031-64719e0d0402.png">

<img width="1103" alt="Screenshot 2020-06-03 at 15 30 25" src="https://user-images.githubusercontent.com/367397/83642479-2bbeb600-a5af-11ea-9ee4-64c3ee94f618.png">

<img width="1109" alt="Screenshot 2020-06-03 at 15 32 33" src="https://user-images.githubusercontent.com/367397/83642706-78a28c80-a5af-11ea-83f8-2d3fdd072b5a.png">
