### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by basz** [harbur/kubernetic#124]
Get https://ddf8c78a-130c-45ab-acdd-2589bbeac37b.k8s.ondigitalocean.com/version?timeout=32s: getting credentials: exec: exec: "doctl": executable file not found in $PATH

Being new it's possible I'm doing something wrong. But it seems to me the Kubernetic.app uses a different $PATH then the CLI user since with the following command I can connect succesfully (`PATH=$PATH open /Applications/Kubernetic.app`). Any other way? 

MacOS latest. Kubernetic v2.4.2

```
which doctl  
/usr/local/bin/doctl
```

```
echo $PATH
/usr/local/opt/node@10/bin:/Users/bas/.yarn/bin:/Users/bas/.config/yarn/global/node_modules/.bin:/Users/bas/bin:/Users/bas/.gem/ruby/2.3.0/bin:/Users/bas/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
```

**Comment by dkapanidis** [comment]
Added on latest release (v2.5.0)

Now on Preferences tab you can configure extra PATH that can be used to locate external binaries such as `doctl`.

<img width="1105" alt="Screenshot 2020-02-22 at 12 30 50" src="https://user-images.githubusercontent.com/367397/75091609-78860000-556f-11ea-9973-9e9c7a9ce3c8.png">
