### ISSUE TITLE
percentage calculation incorrect (limits, quota % used)

### ISSUE THREAD

**Issue by martin2176** [harbur/kubernetic#134]
percentage calculation in limits and quota is incorrect.
for instance 4 used out of 5, shows 133%
1 used out of 5 shows 33%
image pasted below

![image](https://user-images.githubusercontent.com/14482998/74042458-965f3c80-4995-11ea-8ba9-8b8b1acb9a6f.png)

**Comment by dkapanidis** [comment]
Issue is fixed in latest release (v2.5.0)
