### ISSUE TITLE
Where is the Preferences tab?

### ISSUE THREAD

**Issue by noelshebert** [harbur/kubernetic#135]
I just bought a single user license for 30 Euros.  The email arrived and says to cut and paste the key in the Preferences Tab.  Where is the Preferences Tab?  The documentation makes no mention of it. I have clicked on everything.

**Comment by dkapanidis** [comment]
Hi,

The Preference page is not released yet, it will be included in the next release, which will be out in next few days. Until then you don't need the activation license code.

**Comment by melistik** [comment]
I've got the same issue. Trail is fine for me - but i need for accounting an invoice. Where to get it?

**Comment by dkapanidis** [comment]
Hi, 

In latest Kubernetic version (2.5.0) the activation code can now be used on startup of the application.

As for the invoicing, send an email on contact@harbur.io and we'll handle it on Monday.
