### ISSUE TITLE
[Feature request] Dark Mode

### ISSUE THREAD

**Issue by daveio** [harbur/kubernetic#136]
I know it might seem a bit trivial, but a dark theme would really save me some quite literal headaches.

**Comment by OKNoah** [comment]
@daveio Not trivial, mandatory!

**Comment by almottier** [comment]
It would me much appreciated !

**Comment by Asherslab** [comment]
Would also love to see this, the light theme is quite blinding among all my dark themed software

**Comment by ladydascalie** [comment]
Voicing my support and also asking if we could get an update on whether this is being considered or not?

**Comment by dkapanidis** [comment]
yes! Actually this being developed right now. You can see the roadmap on the latest blog post https://blog.harbur.io/announcing-kubernetic-v3-92b5777ff5c4

**Comment by ladydascalie** [comment]
Thanks a lot for the update @dkapanidis, really glad to hear that and thanks for sharing the roadmap!

**Comment by dkapanidis** [comment]
Included in 3.1.0.

Dark mode is here!! 💯 🕶️ 💯 

![dark-mode](https://user-images.githubusercontent.com/367397/101752540-f18c1f00-3ad1-11eb-8a2d-e5a0d9e73f41.gif)
