### ISSUE TITLE
Support for helm TLS and tiller namespace

### ISSUE THREAD

**Issue by AssafShaikevich** [harbur/kubernetic#138]
hi ive tried to use the client in a helm TLS k8s cluster,
when I try to browse the Realeases page , its empty , 
helm configuration  : 
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

We use tiller within namespace , so export TILLER_NAMESPACE=namespace
has to be defined

is there a way to support this ?

**Comment by dkapanidis** [comment]
Kubernetic is now using helm 3 and no longer needs tiller, so closing this
