### ISSUE TITLE
[Feature request] Descriptions when creating things

### ISSUE THREAD

**Issue by OKNoah** [harbur/kubernetic#143]
I've been using Kubernetes a while, but always used an external service (fly.io's Wormhole) for getting it online at a domain name. This has been without issue so far, and is just too easy to not use, not to mention cheaper: https://fly.io/docs/agents/#kubernetes There was a blog post that explained it better but I think it's taken down as they focus on another product. They've said it will continue to be supported, but they're not really maintaining the repo.

Anyway, I've wanted to try use things like Ingress and was happy to see a UI for this; but it lacks any description of what it does, what field is what, examples, etc. "Host"... does this mean the FQDN I want? Obviously I'll look this up and surely find answers, but would be great if more information was on screens like this.

**Comment by dkapanidis** [comment]
fixed on 2.10.0

**Comment by dkapanidis** [comment]
Now all fields contain a (?) icon that hovering provides more information for the specified field:

<img width="1100" alt="Screenshot 2020-08-14 at 15 24 56" src="https://user-images.githubusercontent.com/367397/90253994-55fbe200-de42-11ea-9d29-ecbd8097687e.png">
