### ISSUE TITLE
blank screen - when clicking PV specifications

### ISSUE THREAD

**Issue by martin2176** [harbur/kubernetic#144]
If I select a PV, go into specification view, the application displays a blank white page from which there is no return. Have to quit the kubernetic and launch again. screenshots attached
![image](https://user-images.githubusercontent.com/14482998/77651520-4b988480-6f43-11ea-8388-d9abdcf0e014.png)
![image](https://user-images.githubusercontent.com/14482998/77651540-5226fc00-6f43-11ea-9975-de32471803f0.png)

At this point if I click specifications view. just a blank screen 
![image](https://user-images.githubusercontent.com/14482998/77651607-6a971680-6f43-11ea-9d23-d4647a03f383.png)

**Comment by dkapanidis** [comment]
fixed for next release
