### ISSUE TITLE
Limitranges - incorrectly reporting 

### ISSUE THREAD

**Issue by martin2176** [harbur/kubernetic#146]
Here is my limitranges defined or a namespace. I can attach the yaml which create this limitrange if you want to replicate the issue.
few things readily noticeable which are not reported or incorrectly reported
1. ephermeral storage values are missing
2. persistentvolumeclaim type reports incorrect
below is kubectl command:

C:\D_DRIVE\Azure\AKS\Limits and Quota>kubectl -n small describe limitranges
Name:                  limits-per-container
Namespace:             small
Type                   Resource           Min    Max  Default Request  Default Limit  Max Limit/Request Ratio
----                   --------           ---    ---  ---------------  -------------  -----------------------
Container              cpu                10m    1    50m              150m           3
Container              ephemeral-storage  10Mi   2Gi  100Mi            300Mi          3
Container              memory             10Mi   2Gi  100Mi            300Mi          3
Pod                    memory             10Mi   2Gi  -                -              3
Pod                    cpu                10m    1    -                -              3
Pod                    ephemeral-storage  10Mi   2Gi  -                -              3
PersistentVolumeClaim  storage            100Mi  1Gi  -                -              -

Below is kubernetic display:
![image](https://user-images.githubusercontent.com/14482998/79057064-f474fe00-7c2a-11ea-9c87-fe65f1c1dea7.png)

**Comment by dkapanidis** [comment]
Hi @martin2176,

yes, if you can please share your limitrange YAML so that we can reproduce the example.

**Comment by martin2176** [comment]
---
apiVersion: v1
kind: LimitRange
metadata:
   name: requests-and-limits
   labels:
    namespace-size: small
spec:
    limits:
      - 
        type: Container
        max: #maximum value of  Limits
          cpu: "1000m"
          memory: "2Gi"
          ephemeral-storage: "1Gi"
        min: #minimum value of Requests
          cpu: "10m"
          memory: "10Mi"
          ephemeral-storage: "10Mi"   
        default: #default value of  Limits
          cpu: "100m"
          memory: "200Mi"
          ephemeral-storage: "200Mi"
        defaultRequest: #default value of  Requests
          cpu: "50m"
          memory: "100Mi"
          ephemeral-storage: "100Mi"
        maxLimitRequestRatio: #limit to request ratio should be less than 3
         memory: 2
         cpu: 2
         ephemeral-storage: 2
      - 
        type: Pod
        max: #maximum value of Limits
          cpu: "1000m"
          memory: "2Gi"
          ephemeral-storage: "1Gi"
        min: #minimum value of Requests
          cpu: "10m"
          memory: "10Mi"
          ephemeral-storage: "10Mi"
        maxLimitRequestRatio: #limit to request ratio should be less than 3
         memory: 2
         cpu: 2
         ephemeral-storage: 2
      - 
        type: PersistentVolumeClaim
        max: #max size of PVC
         storage: "10Gi"
        min: #min size of PVC
         storage: "100Mi" 
---

**Comment by dkapanidis** [comment]
fixed for next release (v2.7.0)
