### ISSUE TITLE
[Feature request] Terminal - Selecting a container

### ISSUE THREAD

**Issue by Sonorpearl** [harbur/kubernetic#149]
Especially when two different containers are running in the same pod you can´t use the terminal, since it is just black. It would be nice if you could select the container on which the Terminal session should open.

**Comment by ReneWerner87** [comment]
Feature would be cool

**Comment by dkapanidis** [comment]
done on v2.7.0, pending for publish.

By default it opens the first container in the list, changing the dropdown it closes the open terminal and connects with the selected one:

<img width="564" alt="Screenshot 2020-05-12 at 12 49 45" src="https://user-images.githubusercontent.com/367397/81675585-548bd980-944f-11ea-97c0-5c35a7496a15.png">
