### ISSUE TITLE
Nodes always shown as "Ready" even when they are not

### ISSUE THREAD

**Issue by nikkoura** [harbur/kubernetic#154]
I am using a microk8s cluster with 3 nodes.
When I disconnect one of them, kubectl does report the node as "NotReady", but Kubernetic keep showing the node with a green bar in the nodes' list.

**Comment by dkapanidis** [comment]
the tables have been redesigned to include server-side columns instead of rendering them on client-side, so the issue should no longer apply.

closing, if it still persists don't hesitate to reopen
