### ISSUE TITLE
CronJobs showing data for wrong context

### ISSUE THREAD

**Issue by himslm01** [harbur/kubernetic#157]
I have four contexts available. Some of them have CronJobs, some do not.

When I switch context to one with CronJobs I can see them.

When I switch context to another one without CronJobs I still see the CronJob(s) from the last context.

Noticed on Kubernetic 2.6.0 Linux.

As you can see from this image - according to kubectl the context 'pi13' has no jobs, but Kubernetic is showing one (which actually belongs to another context).

![image](https://user-images.githubusercontent.com/1175979/82186867-6d7b0b80-98e3-11ea-91a1-1dc14201ab33.png)

**Comment by dkapanidis** [comment]
nice catch, the cronjob list was not cleaned up when changing contexts.

fixed for v2.7.0
