### ISSUE TITLE
Accessibility issue with context and namespace drop-down menus

### ISSUE THREAD

**Issue by himslm01** [harbur/kubernetic#158]
I use a pen-and-tablet instead of a mouse.

The drop-down menus to switch context and switch namespace do not have a scroll-bar, so there is no way to scroll them with a pen-and-tablet. You have to use a mouse-wheel scroll (or two-fingered slide on a track pad).

It is impossible for me to select a context or namespace that is not currently visible with a pen-and-tablet interface.

Tested on Linux and Mac with Kubernetic 2.6.0.

**Comment by dkapanidis** [comment]
thanks for the feedback, we'll review it. Until then there is a workaround for that, you can type the first characters of your context/namespace in the dropdown text field and the list will be reduced so that you can select your option.

**Comment by dkapanidis** [comment]
scrollbar is now visible on dropdown menus (to be released on v2.10.0)

<img width="171" alt="Screenshot 2020-07-23 at 08 11 00" src="https://user-images.githubusercontent.com/367397/88256636-1a934b00-ccbc-11ea-85a7-75b8237b5bb5.png">
