### ISSUE TITLE
2.7.0 - Custom Resources: Searching/Filtering doesn't work, don't load

### ISSUE THREAD

**Issue by spyro2000** [harbur/kubernetic#160]
![image](https://user-images.githubusercontent.com/8479925/82319990-cbd2e780-99d2-11ea-8b6a-10e32375aa77.png)

Entering someting in the filter box doesn't reflect on displayed results.
Also clicking on one of those resources just result in a white screen.

**Comment by dkapanidis** [comment]
proper filtering on CRD is now fixed on v2.9.0
