### ISSUE TITLE
[Bug] MacOS: missing icon in status bar

### ISSUE THREAD

**Issue by alexremn** [harbur/kubernetic#161]
Hello there.

Facing also with issue, that there is no icon in status bar in MacOS and there is not option to get rid of it in Kubernetic settings. Can you, please, add an option to show/hide it?
<img width="76" alt="image" src="https://user-images.githubusercontent.com/14985732/82456271-afab7500-9abc-11ea-8d36-49c31f947451.png">

**Comment by dkapanidis** [comment]
fixed missing icon, we won't be adding the option to hide the icon at least for now, the preferences are not available on startup process it would need some rework otherwise.
