### ISSUE TITLE
v 2.8.0 Portforward no longer working after update

### ISSUE THREAD

**Issue by Wesseldr** [harbur/kubernetic#163]
New version installed today v2.8.0 it no longer works to portforward a pod to localhost
Os: Osx 10.5.5
Kubernetic version: 2.8.0
Working through a VPN to my cluster (worked fine in previous verions)
All seems to work but the portforward option just dont generate any portforward or does any response

**Comment by dkapanidis** [comment]
Thanks for the feedback,

will look into that and provide a minor release to fix it

**Comment by Sonorpearl** [comment]
Same on Windows.

**Comment by dkapanidis** [comment]
Fixed on version v2.8.1, will be released today.
