### ISSUE TITLE
Changelog & Documentation links are broken (docs.kubernetic.com)

### ISSUE THREAD

**Issue by Wesseldr** [harbur/kubernetic#164]
Following links do not resolve anymore...

http://docs.kubernetic.com/
https://docs.kubernetic.com/changelog

ping: cannot resolve docs.kubernetic.com: Unknown host

**Comment by dkapanidis** [comment]
We use Gitbook for the documentation and it seems it's currently down https://twitter.com/GitBookStatus/status/1268448791126069248

**Comment by dkapanidis** [comment]
I will update here when the docs are online again

**Comment by dkapanidis** [comment]
It seems that https://docs.kubernetic.com/ is online again.

please reopen if this still persists
