### ISSUE TITLE
Unable to delete jobs after Kubernetic 2.8.0 update

### ISSUE THREAD

**Issue by osvaldolove** [harbur/kubernetic#165]
Hi, using registered version of Kubernetic 2.8.0.

I am unable to delete jobs from the Jobs index page. The `Delete Confirmation` dialog box appears however clicking `Delete`  button does nothing and no errors are reported. Deleting Jobs when opening an individual job does work however.

**Comment by dkapanidis** [comment]
Fixed on v2.8.1, will be released today.

Along with that a list of selected items is now shown when doing a batch delete, as requested per https://medium.com/@krzysztof.m/ive-been-using-kubernetic-since-a-while-now-5964108dbc07
