### ISSUE TITLE
Receiving 'Unauthorized' on cluster that works via kubectl

### ISSUE THREAD

**Issue by joshdcollins** [harbur/kubernetic#167]
I have a cluster (AWS EKS) that I have in my kube/config that works correctly from the commandline.

In Kubernetic, I immediately get an 'unauthorized' message.  Where can I observe logs or something to give me more details on the error?

v2.8.1 on MacOS

**Comment by joshdcollins** [comment]
Root cause was missing path on the 'aws' command.

**Comment by dkapanidis** [comment]
yeah, I was about to propose that but you beat me to it.

If you prefer to avoid updating your ~/.kube/config you can also add the PATH where it is located to the [Preferences](https://github.com/harbur/kubernetic/issues/124#issuecomment-589947589) page.
