### ISSUE TITLE
Unauthorized error message on MacOs & EKS

### ISSUE THREAD

**Issue by djakielskiadesso** [harbur/kubernetic#168]
I got en error message "Unauthorized", when i use current release 2.8.1 and eks 1.16.
![grafik](https://user-images.githubusercontent.com/52488859/85290871-fc0e1a00-b499-11ea-97fd-9342dc32f6e4.png)

Aws cli ist used on MacOS, to get credentials / session token. With kubectl, the conntection works fine and all permissions granted.

Do you have some ideas?

**Comment by dkapanidis** [comment]
Hi,

the error message is not helpful :/ but the usual suspects are normally the following:

- If you use a external binary (in your case `aws`) make sure the full path is in `~/.kube/config` file)
- or you can add the extra location in PATH under preferences page (top right corner icon)
- if you use a proxy to connect to your cluster, you can configure it in the preferences page (it needs restart of app to take effect)

let's see if those help

**Comment by djakielskiadesso** [comment]
Hi,

thanks for the quick response. I missed to add the path location in the settings. So now it works great. But it would be nice, if /usr/local/bin/ could be in path by default.

**Comment by dkapanidis** [comment]
You're right, we'll add it as default value of PATH, this is a common case.
