### ISSUE TITLE
Common tab groups should be open by default

### ISSUE THREAD

**Issue by desaintmartin** [harbur/kubernetic#173]
When launching Kubernetic, all tab groups are closed by default.

Maybe, in order to avoid a click in 90% of situations, the "workload" tab group should be open, and maybe "Configuration" and "Networking" as well.

**Comment by dkapanidis** [comment]
Sticky Menu option is now added on the Preferences which transfers the state of menus (open/closed) to the user, instead of depending on the active page. Menus can be opened/closed and their state is persisted between app restarts.

**Comment by dkapanidis** [comment]
to be released on v2.10.0
