### ISSUE TITLE
Scaling up/down a Deployment/Statefulset from the main list should not change current view to the scaled resource

### ISSUE THREAD

**Issue by desaintmartin** [harbur/kubernetic#174]
In old versions, when scaling up/down a Deployment/StatefulSet from the main list did not cause the current view, allowing to scale up/down several deployments in a few clicks.

Now, scaling it causes the view to change to focus on the scaled Deployment/Statefulset. Maybe it would improve experience to revert this change.

**Comment by dkapanidis** [comment]
fixed on v2.11.0

now actions do not redirect to view screen, instead websocket changes updates dynamically the list.

![scale](https://user-images.githubusercontent.com/367397/91713457-1810f480-eb8a-11ea-8bbc-b4de93caef31.gif)
