### ISSUE TITLE
Allow grep/searching of logs

### ISSUE THREAD

**Issue by chrisjowen** [harbur/kubernetic#178]
Would be nice if the logs could be filtered, searched or grepped against in some way.

**Comment by dkapanidis** [comment]
feature added on v2.11.0

![search](https://user-images.githubusercontent.com/367397/91711967-23aeec00-eb87-11ea-8dc2-062dc2e33bf3.gif)

search is using literal text for now, we'll review potential use of regex for more complex scenarios.

**Comment by dkapanidis** [comment]
duplicate of #210
