### ISSUE TITLE
[Bug] Some issues with 2.9.1

### ISSUE THREAD

**Issue by alexremn** [harbur/kubernetic#180]
After updating to 2.9.1 got several issues:
1. Resources numbers disappeared from left side tabs;
2. Tab groups are not sticky anymore - when selecting new one, previous getting closed;
3. Some issues with terminal - when using bash and typing long commands, its still using small area to show info, not the whole space.

**Comment by alexremn** [comment]
@dkapanidis can you, please, take a look at 1 & 3 from the list above? 2nd one was already answered in another issue.

**Comment by stepanselyuk** [comment]
+ batch resources removing is not working
+ when I remove a resource by using context button, the view goes into default state - filter cleared, pagination reset to 1st page.
