### ISSUE TITLE
issue version  2.9.1 (2.9.1)

### ISSUE THREAD

**Issue by soufianez75** [harbur/kubernetic#184]
the sub-item in the menu cannot be opened at the same time
there is not the number of items in the menu 

![Capture d’écran 2020-07-18 à 10 27 33](https://user-images.githubusercontent.com/15089638/87848508-7424ff80-c8e1-11ea-9ee0-1441d88d2eae.png)

**Comment by cazter** [comment]
Guessing you guys are phasing out Websockets and this is the result? IMO - keep Websockets, just add some connection rebuilds rather than keeping them persistent.

Also, you can no longer see Deployment>Replicasets in this version.

**Comment by dkapanidis** [comment]
Hi,

Thanks for feedback, we're not phasing out websockets, but we're changing the way the underlying connectivity is done. I'll try to explain the websocket change here for future references.

Until now a single session-wide websocket was opened and kept track of all changes. The Websocket was watching a static list of resource types (the ones on the menu at the left). Although this practice was great up to this point, we're favouring a different strategy for websockets for various reasons:

* Reconnection on breaking sessions. If the session-wide websocket was broken for some reason (e.g. wifi reconnection), the updates were left stale and an app restart was necessary. This could be resolved with a heartbeat on websocket for reconnecting.
* Custom Resources: Up till now we had a static-list of resources that were watched from the beginning of the session. So custom resources were not supported. Previous version (2.8.0) used Rest APIs to retrieve CRDs, without websocket support.

Instead now we have the following a more coherent solution with the following:
* Each page is retrieving the resources by Rest API makes it now possible to identify if a list is empty from list is loading.
* Pages use [react-query](https://github.com/tannerlinsley/react-query) for caching, with background reloads and automatic retries on failure.
* Each page is also opening an ephemeral websocket which watches the items for updates, with support for CRDs.

**Comment by cazter** [comment]
Thanks for the explanation @dkapanidis. 

Having multiple menus open is, in my opinion, a key UX feature (i've downgraded back to 2.8.1 because this is missing). Can we expect to this fixed in a future release?

**Comment by dkapanidis** [comment]
That was also reported separately by other users https://github.com/harbur/kubernetic/issues/173 and we will definitely rollback.

The idea is to provide group pages (e.g. Workloads) that will be more useful than directly going to pods, but still for productivity purposes it seems keeping the all menu open by default on startup and letting user setup their states would be the way to go.

**Comment by vasili439** [comment]
@dkapanidis in last release changelog I saw a lot of new features but still there are a lot annoying bugs like described here and #180 #181 #174 . May be it's better to fix current issues before moving forward?

**Comment by dkapanidis** [comment]
@vasili439 thanks for feedback, we're working in parallel to fixing these issues, some are already fixed but were not included to changelog yet (#174, #180.2), the rest (#181, #180.1, #180.3) we'll plan them for next release.

**Comment by vasili439** [comment]
@dkapanidis nice! Thank you! Waiting for the next release :)

**Comment by dkapanidis** [comment]
Included in 3.1.0, by popular request, we've rolled back to the non-folding menu and restated the resource counters on the menu:

<img width="176" alt="Screenshot 2020-12-10 at 10 15 23" src="https://user-images.githubusercontent.com/367397/101751516-a32a5080-3ad0-11eb-801c-a0f5550b26a9.png">

dup #239
