### ISSUE TITLE
Unable to enter license

### ISSUE THREAD

**Issue by prkas** [harbur/kubernetic#185]
I installed v2.9.1 today and was prompted to enter my license. I copied and pasted the license that was provided to me into the field and went to authenticate and it failed.

Now I am unable to try to re-enter the license. I have tried completely removing the app and reinstalling it and cannot find a location to enter it.

**Comment by dkapanidis** [comment]
no worries, you license is correctly configured, otherwise a prompt for trial/license would appear.
