### ISSUE TITLE
Feature request: Make some things configurable

### ISSUE THREAD

**Issue by vasili439** [harbur/kubernetic#186]
Hi! In my opinion it would be nice if a can permanently disable "Show container names" in Logs section or permanently choose terminal type (i.e. sh -> bash) and other features which I need to configure every time when I open Logs and Shell sections.

**Comment by joshdcollins** [comment]
+1 - I find myself unchecking 'Show container names' and changing the count of log lines dozens of times a day.

**Comment by dkapanidis** [comment]
options on preferences have been added to configure default values for the following:

- defaultShell: the default shell to use on Terminal tab
- showContainerNames: show/hide the container names on Logs tab
- defaultLogsSize: default number of lines to show on Logs tab

<img width="1091" alt="Screenshot 2020-08-06 at 14 51 22" src="https://user-images.githubusercontent.com/367397/89533842-52d67580-d7f4-11ea-8a1a-ed1980496872.png">
