### ISSUE TITLE
[Bug] 2.10.0 Workloads > Deployments > Rollouts sorting is string based not numeric

### ISSUE THREAD

**Issue by jim12321** [harbur/kubernetic#199]
Hello.  Paying client here with 8 licenses.  At Colony Networks.

Trying to find the active rollout version is a pain because the rollout name is being sorted by characters rather than integer.  Also you can try and sort on age, but sort appears to not work at all.

Can this bug be fixed?

Thanks.

**Comment by dkapanidis** [comment]
Order of Rollouts is now fixed to be under numeric ordering, to be published at v2.11.0

Though, the screen is not yet watched for updates and the order is fixed at the moment, these will be resolved in next releases.
