### ISSUE TITLE
[Bug] 2.10.0 on MacOS X Refreshing status use to be automatic and now seems more manual in 2.10.0

### ISSUE THREAD

**Issue by jim12321** [harbur/kubernetic#200]
Another behaviour that has seemed to change is it does not refresh as often as it use to.  Do not see any preference to possible change that.

So I would do a deployment via kubectl (outside of Kubernetic) and in previous releases (not sure which version) I would see it change and update within 2-3 seconds.  Now it seems I have to keep clicking on the green Deployment icon to get it to refresh the status so I can see the rollout being applied.

Thanks.

Jim

**Comment by dkapanidis** [comment]
fixed on v2.11.0

now view screens open a websocket to watch resource change for the resource and their children.

![real-time-updates](https://user-images.githubusercontent.com/367397/91712785-c2881800-eb88-11ea-8321-d6b990d5e1c5.gif)
