### ISSUE TITLE
[Feature Request] For Logs view, it would be nice if we could apply a grep to the log stream

### ISSUE THREAD

**Issue by jim12321** [harbur/kubernetic#201]
Love the addition of seeing logs from all pods/containers of a deployment.  That is awesome.

If we could be able to apply a grep to that stream to only show lines that match the grep, that would be nice.

Thanks.

Jim

**Comment by dkapanidis** [comment]
feature added, will be released on v2.11.0


![filter-logs](https://user-images.githubusercontent.com/367397/91168290-afcb9a00-e6d5-11ea-925f-5151000f8c46.gif)
