### ISSUE TITLE
Support for Network Policies

### ISSUE THREAD

**Issue by Kshell11** [harbur/kubernetic#203]
I don't see a way to view network polices. I would have expected to see them in the network tab. I'm new to kubernetic so maybe I haven't looked in the right menu. Is this a planned feature?

P. S. I've been using kubernetic for the past couple of weeks and it's been a really useful tool for checking on cluster status and making simple updates. Nice work 👍 .

**Comment by Kshell11** [comment]
Sweet, I'll keep an eye out for them in a future update.

**Comment by dkapanidis** [comment]
ready, will be released on v2.11.0
