### ISSUE TITLE
MacOS binary not properly signed.

### ISSUE THREAD

**Issue by databus23** [harbur/kubernetic#21]
I just wanted to try the kubernetic app for MacOS and deleted it directly after the first double click as its not signed with a proper  apple developer certificate.

**Comment by spiddy** [comment]
Hi, thanks for the feedback, the certificate will be updated soon to be a proper apple developer certificate. Will notify when it is released here

**Comment by databus23** [comment]
Thanks!

**Comment by spiddy** [comment]
Kubernetic is now signed with proper certificate.
