### ISSUE TITLE
Events not ordered by time by default.

### ISSUE THREAD

**Issue by ashb** [harbur/kubernetic#22]
Looking at the "Events" tab of the node after I cycled some nodes (which I don't think is relevant) I noticed the events were not totally ordered. The event age went "8m, 4m, 4m, ... 4m,  1m, 4m, 5m, 1m, 3m, 5m, 7m, 1h, 1h. etc."

**Comment by ashb** [comment]
Oh, forgive me. They were ordered by the name by default.

**Comment by spiddy** [comment]
Reopening as it makes sense,

events should be time-ordered by default. Otherwise the events will appear out of logical order.

**Comment by dkapanidis** [comment]
Resolved for next release (4.2.0)

see #360 for more details
