### ISSUE TITLE
Cannot activate using license from email

### ISSUE THREAD

**Issue by grzegorzkurtyka** [harbur/kubernetic#236]
Just bought a "desktop licence" and looks like activation key form email is not working.
I had previously installed that app, and evaluation is on "0 days left", but pasting a licence key from email `ey...` leaves the activation code box red and "activate" button disabled.
Console logs:
```Update for version 2.12.0 is not available (latest version: 2.12.0, downgrade is disallowed).
time="2020-09-16T12:29:35+02:00" level=info msg="[POST] /api/license/validate 200 (1ms)" latency=1 method=POST params= path=/api/license/validate statusCode=200
time="2020-09-16T12:29:37+02:00" level=info msg="[POST] /api/license/validate 200 (1ms)" latency=1 method=POST params= path=/api/license/validate statusCode=200
time="2020-09-16T12:29:38+02:00" level=info msg="[POST] /api/license/validate 200 (1ms)" latency=1 method=POST params= path=/api/license/validate statusCode=200```

Version is 2.12.0 (as visible in logs)

**Comment by dkapanidis** [comment]
Hi @grzegorzkurtyka,

yes I've already sent you an email with the issue, we located it, and we're working on sending you a valid licence code

**Comment by gregq** [comment]
Thanks for handling that issue. New license key works perfectly
👍

**Comment by dkapanidis** [comment]
No prob, have a nice day, closing the issue as fixed
