### ISSUE TITLE
Values text box in release edit is too small on Mac OS

### ISSUE THREAD

**Issue by tsvgos** [harbur/kubernetic#238]
Values text box in release edit is too small on Mac OS

Mac OS version: Catalina 10.15.6
<img width="1051" alt="Screenshot 2020-09-18 at 13 36 19" src="https://user-images.githubusercontent.com/4478865/93593443-6a3c7d00-f9b4-11ea-8139-8bc61cbf3c26.png">

**Comment by dkapanidis** [comment]
Thanks for feedback, we'll look into it
