### ISSUE TITLE
Important Features Removed

### ISSUE THREAD

**Issue by cazter** [harbur/kubernetic#239]
We've been stuck on version 2.8.1 because the newer versions are missing vital features for our clusters.

- Object counts in the nav menu: We run dozens of namespaces with autoscaling enabled on each. We need to be able to click through the namespaces and get a quick sense for the current scale of the environment.
- Navigation menu's closing: Only the selected nav menu remains open--with those not in focus auto-closing. Associated with the above, this slows what would otherwise be a quick review of a namespace.

**Comment by dkapanidis** [comment]
Included in 3.1.0, by popular request, we've rolled back to the non-folding menu and restated the resource counters on the menu:

<img width="176" alt="Screenshot 2020-12-10 at 10 15 23" src="https://user-images.githubusercontent.com/367397/101751516-a32a5080-3ad0-11eb-801c-a0f5550b26a9.png">
