### ISSUE TITLE
[Feature Request] - "Pods" tab for Nodes

### ISSUE THREAD

**Issue by reubenavery** [harbur/kubernetic#258]
It would be really great to have a "Pods" tab when viewing specific Nodes that lists all the Pods, and it would be SUPREMELY great if there could be columns showing memory and cpu averages and disk utilization!

**Comment by dkapanidis** [comment]
You can currently see the list of pods on the node status tab, below the node itself. The list includes pods from all namespaces that are assigned to specific node:

<img width="1117" alt="Screenshot 2020-12-10 at 10 28 15" src="https://user-images.githubusercontent.com/367397/101753240-afafa880-3ad2-11eb-9b08-fdbfe2970d6d.png">

Also, for resource consumption we now have cpu and memory usage (same as `kubectl top nodes`) embedded on the table:

<img width="1104" alt="Screenshot 2020-12-10 at 10 29 22" src="https://user-images.githubusercontent.com/367397/101753146-9a3a7e80-3ad2-11eb-9fb8-395f959f516a.png">

cpu & memory columns can be disabled from the preferences sections if needed (opt-out):

<img width="1102" alt="Screenshot 2020-12-10 at 10 31 57" src="https://user-images.githubusercontent.com/367397/101753556-13d26c80-3ad3-11eb-8ba7-dc0ebc901425.png">

**Comment by dkapanidis** [comment]
as for disk utilization I'm not sure there is a standard yet, any ideas are welcome for inclusion of course.
