### ISSUE TITLE
Log Font

### ISSUE THREAD

**Issue by joshdcollins** [harbur/kubernetic#261]
I recently updated to 3.0.0 and the logs are no longer using a fixed width font -- this makes certain logs harder to read.  Can this please be reverted or made configurable?

Thanks!
![image](https://user-images.githubusercontent.com/12936758/98716077-f89c0200-2358-11eb-8b7b-40ac8183ab88.png)

**Comment by dkapanidis** [comment]
Hi, thanks for feedback it will certainly be rolled back to fixed-width font on next release, the change of font here was unintentional.

**Comment by dkapanidis** [comment]
Monospaced fonts are fixed for next release (`3.1.0`)

Also fixed an issue where multiple spaces where squashed together visually by adding `white-space: pre-wrap;` to the styling of the logs.

<img width="1107" alt="Screenshot 2020-11-11 at 10 51 16" src="https://user-images.githubusercontent.com/367397/98796688-f2b32900-240b-11eb-93ed-952f9eb89cb8.png">
