### ISSUE TITLE
Incorrect events ordering

### ISSUE THREAD

**Issue by constantable** [harbur/kubernetic#265]
Last seen column ordering is incorrect. Deployments -> Events tab

Should be 

- 6m24s
- 6m24s
- 7m
- 7m1s
- 35m

and so on and vice versa

![image](https://user-images.githubusercontent.com/11844178/98846638-b235c880-2468-11eb-9a0f-945d55a874b4.png)

**Comment by constantable** [comment]
And the same thing for the **AGE** column of the **Pods** section

**Comment by dkapanidis** [comment]
Date related columns such as `Last Seen`, `Age` or `Created By` need some tinkering for ordering purposes and real-time updates. They are currently displayed as string format rendered server-side by Kubernetes in relative-to-now time, e.g. `5m`, `36m`, `1h`. (except "Created By" which is already in fixed timestamp).

In order for them to be ordered properly they should be converted to fixed timestamp and converted back to relative-to-now time for visualization.

This process would also make recent events (e.g. `5s` -> `6s`) to update real-time without new data flowing in.

**Comment by hcharley** [comment]
Just wanted to chime in to say that having this would help for particular usecases, like seeing older deployments vs newer deployments. Wondering if there is a development push coming up that the devs would mind addressing this in?

**Comment by dkapanidis** [comment]
Resolved for next release (4.2.0)

see #360 for more details
