### ISSUE TITLE
3.0.1 not updates values fast as was in 2.x

### ISSUE THREAD

**Issue by stepanselyuk** [harbur/kubernetic#267]
Hello,
I miss one of the main features which attracted me to the product: it shows changes instantly using WebSockets, so I was able even to see issues with HPA cause pods went crazy. Now I see it refreshes once for a while, like 7 seconds. Or it even hangs and I need to click on the resource name to run a refresh.

**Comment by dkapanidis** [comment]
What is your Kubernetes version?

I may be wrong, but it seems you're using a kubernetes version below 1.15.0.

New version is streaming the data from kubernetes in table format, and below 1.15.0 streaming in table format was not providing all columns, not much that can be done there. So why was it working before? The data was static and calculated client-side by the object itself depending the type of object.

**Comment by dkapanidis** [comment]
If your Kubernetes version is an old one, do you plan an upgrade soon? otherwise I'd propose to stick with v2 until you upgrade your cluster.

**Comment by stepanselyuk** [comment]
@dkapanidis The cluster in question is 1.15.xx

**Comment by dkapanidis** [comment]
hm, can you provide me the exact version so I can test it locally? it should be working properly but I'd like to test it.

**Comment by stepanselyuk** [comment]
@dkapanidis 
```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dkapanidis** [comment]
I'll do some testing locally, to see if I can locate the issue, can you also post what's your kubernetes/cloud provider?

**Comment by stepanselyuk** [comment]
It is an on-prem cluster, should be a default distribution, I did not set up it, so don't have many details.

**Comment by dkapanidis** [comment]
that's ok, I'll launch a minikube and do a fast test, it may be possible 1.15.x doesn't support v1.Tables yet and needs to be more recent.

**Comment by dkapanidis** [comment]
That's odd, it works ok for me using a fresh cluster with minikube (1.15.6)
![test](https://user-images.githubusercontent.com/367397/99085140-233fc200-25c8-11eb-9b0a-e1536ef3d947.gif)

**Comment by dkapanidis** [comment]
Is there anything else custom in your setup?

- Do you use PROXY config to connect to the cluster?

**Comment by stepanselyuk** [comment]
In my kubeconfig I don't see any `PROXY`.

**Comment by stepanselyuk** [comment]
Ok I will see further, maybe it was a temporary issue, thank you

**Comment by dkapanidis** [comment]
ok, closing for now, if the problem persists reopen so we can further investigate
