### ISSUE TITLE
[Feature Request] add tooltips to the action buttons

### ISSUE THREAD

**Issue by hbinkle** [harbur/kubernetic#268]
Please add tooltips to action buttons.
I'm new to the tool and don't know what button does which action.
![image](https://user-images.githubusercontent.com/51942180/99261420-fe905800-281c-11eb-90bc-bc512ac01039.png)

**Comment by dkapanidis** [comment]
added for next release

<img width="1102" alt="Screenshot 2020-11-19 at 13 42 02" src="https://user-images.githubusercontent.com/367397/99667669-06ded200-2a6d-11eb-9ca1-73c3f219bd26.png">
