### ISSUE TITLE
Unable to scroll through namespaces

### ISSUE THREAD

**Issue by Platzii** [harbur/kubernetic#27]
You are unable to scroll in Settings > Namespaces when having a lot of namespaces.
The same issue occurs in the list at the top menu bar.

**Comment by Platzii** [comment]
Looks like in 2.0.11 the list at the top has been reworked and is scrollable (and searchable!) now 👍 

Now only the page in Settings > Namespaces remains.

---

Btw, I noticed the namespaces are sorted in a kind of random way and I seem to be unable to sort them alphabetically by clicking the table headers. Should I create a new issue for this?
Same problem on the Settings > Contexts page.

**Comment by spiddy** [comment]
Hi,

thanks for the feedback! Settings > Namespaces is scrollable, and the sortable on the next (unreleased yet) release v2.0.13.

I'll notify here when the release is published

**Comment by spiddy** [comment]
Release v2.0.13 is out
