### ISSUE TITLE
[Feature Request] text size adjustments for logs

### ISSUE THREAD

**Issue by MrQuiX** [harbur/kubernetic#273]
On MacOS, logs use a much larger font size than the default editor reducing density.  Could we get a default log font size preference?  A simple dropdown with a few options would be fine.

**Comment by dkapanidis** [comment]
added zoom-in, zoom-out and reset buttons on app, with keyboard shortcuts. That should be sufficient to configure per preference. I don't think decoupling logs size from the rest of the app fonts is necessary, would that be sufficient?

![zoom](https://user-images.githubusercontent.com/367397/101830647-22ea0680-3b35-11eb-8148-061e55ee01c9.gif)

**Comment by dominch** [comment]
v3.2 is still not released? Can't find this anywhere :/

Interface font is ok, would be that a problem to allow font family and size for logs section selectable on settings page? 
Personally I preffer Andale mono font and use that one on all my terminals, those logs has way to big font for me, but interface is OK.

**Comment by dominch** [comment]
Logs and terminal font should be configured separately and not tight with interface font size. 

Take a look at this here, I changed font to 0.6em on this screen, interface font would be unreadable with this scale. 

![image](https://user-images.githubusercontent.com/10815109/106121024-5faaa500-6157-11eb-922e-2000086968a4.png)
