### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by monocle-tech** [harbur/kubernetic#282]
Cannot download the app from the kubernetic landing page

**Comment by dkapanidis** [comment]
That's strange, I just tested and it works for me ok. Which OS link was broken, Mac, Win or Linux?

can you try the direct link from [here](https://kubernetic.s3.amazonaws.com/Kubernetic-3.1.0.dmg), does this work?

Which country are you located at?

**Comment by monocle-tech** [comment]
I am running on MacOs 10.15.7.  Trying to download with Google Chrome (Version 87.0.4280.141)

Here is a screenshot of the dev console

**Comment by nfodor** [comment]
Paid for a license :-) no answer after 3 weeks when license does not register. So I was hoping to be able to compile the source somewhere but that's only the docs.

**Comment by dkapanidis** [comment]
Hi @nfodor  I just sent you a response by email regarding your licensing issue.

@monocle-tech the screenshot was not attached here, so I can't see the problem. can you re-upload and answer on the following questions?

* can you try the direct link from [here](https://kubernetic.s3.amazonaws.com/Kubernetic-3.1.0.dmg), does this work?
* Which country are you located at?

**Comment by dkapanidis** [comment]
closing as I can't reproduce. If issue still persists please followup by reopening the issue and providing more feedback.

**Comment by nfodor** [comment]
> Hi @nfodor I just sent you a response by email regarding your licensing issue.
> 
> @monocle-tech the screenshot was not attached here, so I can't see the problem. can you re-upload and answer on the following questions?
> 
> * can you try the direct link from [here](https://kubernetic.s3.amazonaws.com/Kubernetic-3.1.0.dmg), does this work?
> * Which country are you located at?

ok thanks just saw the email, busy at work had no time to check, will try and respond by email!
