### ISSUE TITLE
Strange sort by age

### ISSUE THREAD

**Issue by stepanselyuk** [harbur/kubernetic#285]
Hello,
I see the application cannot sort by age field properly. I attached a couple of screenshots here.

<img width="111" alt="Screenshot 2021-01-28 at 2 12 05 PM" src="https://user-images.githubusercontent.com/2071269/106137354-457ec000-6173-11eb-8796-72430d408586.png">
<img width="104" alt="Screenshot 2021-01-28 at 2 11 53 PM" src="https://user-images.githubusercontent.com/2071269/106137360-46afed00-6173-11eb-85e1-fbd46f5cac72.png">

**Comment by dkapanidis** [comment]
related to this: https://github.com/harbur/kubernetic/issues/265#issuecomment-725599301

**Comment by dkapanidis** [comment]
Resolved for next release (4.2.0)

see #360 for more details
