### ISSUE TITLE
Last item in 'Nodes' not visible

### ISSUE THREAD

**Issue by Platzii** [harbur/kubernetic#29]
When having more nodes than can fit on 1 page, a scroll bar appears but when scrolling all the way down, the last item is not visible.

**Comment by spiddy** [comment]
Thank you for the report. We'll review the scrolling issue soon

**Comment by spiddy** [comment]
Related to #27

**Comment by spiddy** [comment]
Scrolling is now working properly in case the window is reduced height

Also, there is now pagination added when many items exist on a page
