### ISSUE TITLE
Kubectl config editor

### ISSUE THREAD

**Issue by eljoth** [harbur/kubernetic#292]
A component which enables to add/remove/edit clusters in Kubernetic itself would be awesome!

**Comment by dominch** [comment]
Or just open any (system) editor to allow edit and save that.

**Comment by eljoth** [comment]
If you are having a lot of clusters because you are having a lot of projects with different stages it is pretty awful to add a new cluster or remove one manually in an editor since they are not grouped clusterwise but by context, cluster, user.

**Comment by mrjamiebowman** [comment]
This would be a really useful feature. I just went into the contexts and saw a bunch of contexts that I no longer use. I would love to be able to right-click delete. While I can use a text editor that's a real pain in the butt compared to the suggested feature.
