### ISSUE TITLE
On update older things disappears

### ISSUE THREAD

**Issue by Whazor** [harbur/kubernetic#293]
For everything I see within the kubernetes cluster the following happens: resource updates, then afterwards the older existing resources disappear.

Running Kubernetic 3.1.0, on k3s 1 node cluster v1.20.2+k3s1. I tried disabling metrics as well.

**Comment by Whazor** [comment]
Seems like the problem is gone when you have more than one node

**Comment by Whazor** [comment]
Disregard last comment, the problem went away when I installed cluster with k3sup which uses k3s v1.19.8+k3s1 instead of the latest 1.20. So something in the latest k3s is incompatible with kubernetic.

**Comment by Whazor** [comment]
Closed in favor of #309

**Comment by dkapanidis** [comment]
This issue is now resolved on `v3.2.0`
