### ISSUE TITLE
Add the ability to copy text from the terminal window

### ISSUE THREAD

**Issue by vikimaf** [harbur/kubernetic#295]
![image](https://user-images.githubusercontent.com/49949779/110113607-6797dd80-7dc4-11eb-9554-9f137b51a49c.png)

I want to be able to copy text from the output in the console `123`.

**Comment by AlexRabtsevich** [comment]
Oh, I think this is a cool feature. I would like to use it if it is possible to implement this

**Comment by stepanselyuk** [comment]
I remember it was working till some moment, and then stopped working (windows, Linux). Recently once (probably after a restart), on Ubuntu, I got it worked, but then it stopped working again. Following restarts did not help. In Lens, I don't have such an issue.

**Comment by stepanselyuk** [comment]
@dkapanidis do you have any plan to fix this? I'm facing with this every day and have to use screenshots (Ubuntu 21.10, kernel 5.16.11)

**Comment by dkapanidis** [comment]
fixed on `4.0.0`

this is a dup of #169 see my comment [here](https://github.com/harbur/kubernetic/issues/169#issuecomment-1094921397) for more details.
