### ISSUE TITLE
CPU/Memory resources don't show - maybe I have to configure something extra?

### ISSUE THREAD

**Issue by tmvtmv** [harbur/kubernetic#298]
Hi,

For none of the clusters I'm attaching to I don't get to see information about CPU and Memory. This is the same for both Nodes as Pods. Am i doing something wrong or is this something need fixing in Kubernetic?

![Screenshot 2021-03-24 at 15 45 55](https://user-images.githubusercontent.com/28952111/112331422-2f940400-8cb9-11eb-9426-f0edbcf5e406.png)

Thanks!

Kind regards,
Ties Voskamp

**Comment by dkapanidis** [comment]
You need to activate metrics-server on your cluster for the metrics to appear. A quick way to test this is to see if your CLI works:

```sh
kubectl top pods
kubectl top nodes
```

You can disable the CPU,MEMORY columns from the preferences if you don't have your cluster setup for metrics.

**Comment by tmvtmv** [comment]
Ah, the metrics-server did it. Thanks for the very, very fast reply!
