### ISSUE TITLE
Find does not show text in search box

### ISSUE THREAD

**Issue by pinkfloydx33** [harbur/kubernetic#305]
When searching a resource's YAML with <kbd>Ctrl+f</kbd>, the search box does not show the text you type. Searching *does* work, you just cannot see the text you've typed. 

In the screen shot below, I've typed the text `metadata`, but as you can see the search box doesn't actually represent that.

![image](https://user-images.githubusercontent.com/395615/113477267-a9ad5100-944e-11eb-9f64-f517044073d9.png)

Kubernetic 3.1.0
Windows 10 x64

**Comment by dkapanidis** [comment]
Fixed on `4.0.0`

![Screenshot 2022-04-11 at 12 57 02](https://user-images.githubusercontent.com/367397/162726106-e86fd554-9656-436b-9dbd-e375f421339e.png)
