### ISSUE TITLE
Purchase invoice and business contact

### ISSUE THREAD

**Issue by maraswrona** [harbur/kubernetic#306]
Hello

On 24th of March I bought 1 personal license for Kubernetic desktop from your website https://www.kubernetic.com/ - I have done this providing our company email and VAT ID. However, we haven't received any invoice regarding this purchase yet. I have also sent you an email at contact@harbur.io on 30th of March - unfortunately without any response. 

I don't know what else I can do and how otherwise to contact your company, so I'm opening this issue here. Hopefully someone will respond.

Kind regards,
Marek

**Comment by dkapanidis** [comment]
Closing as this is resolved by email and invoice is sent
