### ISSUE TITLE
Kubernetic not working with Control Plane of 1.20.x

### ISSUE THREAD

**Issue by pinkfloydx33** [harbur/kubernetic#309]
Kubernetic is not working properly after upgrading the control plane of 1.20.x. This may be related to #293 but I am not sure.

I just upgraded my AKS cluster to v1.20.5. Now, once you click on any action next to a resource (such as "restart" next to a Deployment), the majority of the screen will disappear. You then need to re-navigate back to see all the resources again. On most other screens (deployment->pods, nodes, Secrets, ConfigMaps) the resources themselves disappear and then (sometimes) re-appear just by navigating to the page (no action button required). In most all cases its impossible to view any of the resources. 

See this video clip which demonstrates:
- Deployments disappearing when a different deployment has it's action buttons pressed
- The Pods "sub-page" for Deployments showing 
  - same action button behavior, and  
  - pods flickering, refreshing funny and almost never displaying everything at once

https://user-images.githubusercontent.com/395615/117144962-9577af00-ad80-11eb-80b5-5c2f4058fc19.mp4

Using a second cluster, I've validated that this occurs after migrating the control plane from 1.19.x -> 1.20.x. It did not occur in 1.19.9  but does occur in 1.20.2 and 1.20.5. The version running on the nodes themselves does not appear to make a difference.

This has rendered Kubernetic **entirely useless**. I've tried downgrading/upgrading `kubectl`  and removing all Kubernetic and kubectl caches. I've also removed metric server/scraper (based on the comments in #293) but none of that helps.

**Comment by jeroenbegyn** [comment]
I'm experiencing the same kind of issues. It also started after the 1.19.x -> 1.20.x update.

**Comment by Whazor** [comment]
I can confirm this is the same behavior as in my issue #293, indeed migrating to k8s 1.20.x makes Kubernetic entirely useless. I would really appreciate a patch solving this. cc @dkapanidis

**Comment by dominch** [comment]
I just hit this bug too and came here to report it :( 
Hope that new release will fix this!

**Comment by alexandersm** [comment]
Got similar problem after the cluster upgrade to 1.20

**Comment by lbguilherme** [comment]
This seems most likely related to the fact that 1.20 removed `metadata.selfLink`. Kubernetic should now generate this link from the resource type, version and name.

**Comment by dkapanidis** [comment]
That's great catch!`metadata.selfLink` is certainly used in Kubernetic, I will check and see if a patch can be provided soon.

**Comment by agronholm** [comment]
I saw this happening even on Kubernetes 1.18.

**Comment by mikovsky** [comment]
Any updates?

**Comment by jeroenbegyn** [comment]
Any updates?

**Comment by francoisminaud** [comment]
There is a temporary workaround for those who run Kube 1.20.x and have access to their Control Plane API Server configuration.

You may configure the  `RemoveSelfLink` Feature Gate to false.

Here is our 1.20.x for reference (/etc/kubernetes/manifests/kube-apiserver.yaml)
`- --feature-gates=EphemeralContainers=true,RemoveSelfLink=false`

Do that on all masters in case your API Server is in HA mode.

AFAIK this is only a bandaid and will not be working in Kube 1.21+

**Comment by francoisminaud** [comment]
@dkapanidis This was tackled by Lens : https://github.com/lensapp/lens/pull/1804#pullrequestreview-555290086

We like Kubernetic and would love to keep using it (and moreover paid for the licence), I hope you can work on it at some point.

**Comment by pinkfloydx33** [comment]
Paid for a license and am incredibly saddened. No access to control plane (AKS) and on 1.21 already. Any update... Even a "won't fix" so I can stop hoping would be appreciated

**Comment by gabrielsyapse** [comment]
me too, i use it every day even though it's broken and don't want to use another gui.

**Comment by dkapanidis** [comment]
The new release is finally out 🥳 

It fixes the issue by removing any references to the now removed `metadata.selfLink` field and instead it uses `metadata.uid` to uniquely identify objects.

For those setting the feature gate `RemoveSelfLink=false` this will no longer be necessary once you update your clients.

For more details of the release you can check the [changelog](https://docs.kubernetic.com/changelog.html)

I believe some apologies are due here, because my timing to resolve this was far from ok. The app development was on pause for quite some time while I'm doing consulting work elsewhere, but I should have taken the necessary time to resolve this in a more timely fashion way.

I'm planning to reactivate the development of Kubernetic since I see there is a continued interest of the app.
