### ISSUE TITLE
Is this project already deprecated?

### ISSUE THREAD

**Issue by alexremn** [harbur/kubernetic#313]
Good day!
Is this project still alive?
No changes been made for a long long time..

**Comment by dominch** [comment]
I hope it's not deprecated, also looking forward for update for k8s 1.20.x  and few bugfixes :)

**Comment by MrQuiX** [comment]
Feeling dumb about paying for a full license when release cadence is this bad.

**Comment by alexremn** [comment]
Previously it was good, but something appeared to be broken months ago. Its really frustrating.

**Comment by Infusible** [comment]
plz, give my money back dkapanidis)

**Comment by dkapanidis** [comment]
The project is not deprecated, there are new features coming up as a major release and bug fixes in the backlog for the existing release to solve some of the common pain points.

Hi @Infusible, we have a 30-day no-questions-asked refund policy, please send me an email at contact@harbur.io with your license key and we'll proceed with revocation and refund.
