### ISSUE TITLE
Activation is broken

### ISSUE THREAD

**Issue by renier-rhode** [harbur/kubernetic#315]
I purchased an additional license for Kubernetic and received an activation code.

However it refuses to activate. The activate button remains disabled.

**Comment by dkapanidis** [comment]
Please make sure the following to avoid activation issues:

**Comment by renier-rhode** [comment]
@dkapanidis Thank you, I managed to get it working. I had a similar issue on my other machine.

The important part is to remove the whitespaces and newlines BEFORE you paste it in the input box. 

The activate button won't enable if you remove the whitespace and lines after pasting.
