### ISSUE TITLE
Issue with editing ingress and deployment on 1.15 and 1.21

### ISSUE THREAD

**Issue by stepanselyuk** [harbur/kubernetic#320]
In 1.15 I cannot edit a deployment before I put apps/v1 as API version (and anyway it's not saving cause you cannot change the API version of an object without recreation of it).

In 1.21 I have the opposite problem: it's not working with networking/v1 and wants networking/v1beta1.

Another thing is I have paid for the license and suggested a few people use Kubernetic and buy the license. Now I feel guilty before them because this software has many bugs and does not get updates for a while. And also limited support of Linux. Man, we are DevOps/SRE/SA, many of us working in Linux.

**Comment by dominch** [comment]
@dkapanidis any plans for update? No new release since december and more bugs like those :( I'm checking update button each day and need to go back to console each day. Any roadmap and release date?

**Comment by dkapanidis** [comment]
Hi @dominch, @stepanselyuk

There are plans for update but I can't confirm on release date just yet, it will be at least 1 month before new release is out.

**Comment by dominch** [comment]
Will there be any hotfix earlier before new release? Is there any beta version to test (and help)?

**Comment by Infusible** [comment]
@dkapanidis, any update?

**Comment by dkapanidis** [comment]
Fixed on version `v3.3.0` (released on 22 Feb).

Explained on blog post [here](https://www.kubernetic.com/blog/release-3-3-0):

>Issue with editing ingress and deployment on 1.15 and 1.21
>
> Some API calls were using specific resource API versions by leveraging the typed API calls of [kubernetes/client-go](https://github.com/kubernetes/client-go) but this caused issues for clusters too old or too new where the static API versions have been deprecated. Kubernetic now has a fully featured REST-based client with dynamic API versions to avoid these versioning issues.

This makes it functional for both old (e.g. 1.15) and new (e.g. 1.21) API versions.
