### ISSUE TITLE
Kubernetic Issues following EKS 1.21 (K8S 1.21) upgrade

### ISSUE THREAD

**Issue by cazter** [harbur/kubernetic#325]
Kubernetic 3.1.0.

Any workloads in a state other then ready/healthy are NOT displayed within EKS 1.21.

This doesn't occur with within our clusters that are still running EKS 1.19.

**Comment by cazter** [comment]
Any info on this?

**Comment by cazter** [comment]
@dkapanidis halp pls?

**Comment by cazter** [comment]
getting worried.

**Comment by dkapanidis** [comment]
This is now solved on `v3.2.0`.

This is a duplicate of [#309](https://github.com/harbur/kubernetic/issues/309#issuecomment-1026826094), please check the my comment there for more details.
