### ISSUE TITLE
Is the project abandoned??

### ISSUE THREAD

**Issue by ptuchik** [harbur/kubernetic#326]
Hi,

I want to know if the project is abandoned? There are lots of bugs with Kubernetes new versions, but there are no updates from Kubernetic to fix at least the part of them. It is totally unusable with Kubernetes 1.20+

**Comment by francoisminaud** [comment]
There is a temporary workaround for those who run Kube 1.20.x and have access to their Control Plane API Server configuration.

You may configure the  `RemoveSelfLink` Feature Gate to false.

Here is our 1.20.x for reference (/etc/kubernetes/manifests/kube-apiserver.yaml)
`- --feature-gates=EphemeralContainers=true,RemoveSelfLink=false`

Do that on all masters in case your API Server is in HA mode.

AFAIK this is only a bandaid and will not be working in Kube 1.21+

**Comment by lbguilherme** [comment]
@dkapanidis / @Spiddy / @tigauaharbur / @JuankaHarbur, if there is no intention of maintaining and updating Kubernetic to fix the numerous issues, then please consider open-sourcing it so we as a community can fix it.

I paid for the product and I think it is better than the alternatives. But I'm being forced to abandon it because of many simple-to-fix issues...

**Comment by Marusyk** [comment]
any updates?

**Comment by francoisminaud** [comment]
Got in touch with the maintainer. He said an update will be available soon (didn't get an exact date) so we have to stay tuned.

For cluster 1.20+, I am forced to use Lens but I really don't like it's UI. Hopefully the Kubernetic update will be here soon (Christmas maybe? :) ).

**Comment by dkapanidis** [comment]
New release `v3.2.0` is out that fixes the issue [#309](https://github.com/harbur/kubernetic/issues/309#issuecomment-1026826094), please check my comment there for more details regarding active development.
