### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by YunaBraska** [harbur/kubernetic#329]
I am tinting of using this tool for my team but I am a bi scared since the lastest release is one year ago. Is there any news about the project status. E.g. currently I can only start Kubernetic via command line when I want to use it with EKS using MacOs...

**Comment by SergeBud** [comment]
you can try LENS then :-)

**Comment by jim12321** [comment]
https://github.com/harbur/kubernetic/issues/326 

In that issue someone posted that he will be making an update.  But certain as of right now this product does not work for 1.20/1.21 k8s clusters.  :(

**Comment by YunaBraska** [comment]
@SergeBud LENS is not the same :/ 
@jim12321 does it also not work when you start it from the console? I don’t know my version but a console start works for me.

**Comment by AleksdemSA** [comment]
I think so. I can't activate the license, the bugs aren't fixed. Too bad, this is a very convenient tool!

**Comment by dkapanidis** [comment]
New release `v3.2.0` is out that fixes the issue [#309](https://github.com/harbur/kubernetic/issues/309#issuecomment-1026826094), please check my comment there for more details regarding active development.

@AleksdemSA did you manage to activate the license? check [this](https://github.com/harbur/kubernetic/issues/330#issuecomment-997479239) comment for more details regarding activation issues.
