### ISSUE TITLE
Start of Linux Version Has Connectivity Issue

### ISSUE THREAD

**Issue by DarveyLavender** [harbur/kubernetic#331]
Error found: ENOENT: no such file or directory, open '/opt/src/Kubernetic-3.1.0/resources/app-update.yml'

**Comment by jirkace** [comment]
that is not connectivity issue, but missing file (app-update.yml) in Linux version
#314 , #257

**Comment by dkapanidis** [comment]
Resolved on release `3.2.0`.

Now the linux can be auto-updated and it doesn't display the above error message anymore.

* Linux [downloadable](https://kubernetic.s3.amazonaws.com/Kubernetic-3.2.0.AppImage) is now an `AppImage` format. 
* Tarball is also available for the `3.2.0` release [here](https://kubernetic.s3.amazonaws.com/Kubernetic-3.2.0.tar.gz).

If there are no issues with AppImage, in following releases it will be the default and only linux distributable.

**Comment by dkapanidis** [comment]
Depending the interest we may add more formats:

If there is interest for `tar.gz` please upvote this comment.

**Comment by dkapanidis** [comment]
If there is interest for `rpm` please upvote this comment.

**Comment by dkapanidis** [comment]
If there is interest for `deb` please upvote this comment.

**Comment by jirkace** [comment]
Tarball version does not contains `resources/app-update.yml` so this tarball version, this error **persists **in tarball version****
****AppImage** version is OK**, thank you for fix!
