### ISSUE TITLE
Bug: Lifetime licenses don't work anymore in 3.3.0.

### ISSUE THREAD

**Issue by Sonorpearl** [harbur/kubernetic#336]
Lifetime licenses don't work anymore:
"Your Activation code has expired. To renew your license click on "Buy License" button below."

**Comment by dkapanidis** [comment]
Hi,

Licenses until recently were perpetual with one-year free updates, but the one-year updates was never enforced. This is now activated, if you want to keep using the license without the updates you can download the previous version.

This has been described in more details in today's [blog post](https://www.kubernetic.com/blog/release-3-3-0).

Also there is active discount for updates until the end of March for pre-existing clients, simply send a message from the email used for purchasing the license to contact@harbur.io and we'll send you the discount promo.
