### ISSUE TITLE
License issue!!!!!

### ISSUE THREAD

**Issue by ptuchik** [harbur/kubernetic#337]
Heyy!!!
What's going on???? When I bought the license it was lifetime, now it is showing as expired and suggests to buy another one )))))
Really? :D

You decided to earn money with scam? Where is the promise? )) There are millions of free alternatives with more features, I just loved your work and paid for license, even that time the free and paid versions were identical, and this is now the appreciation? ))

**Comment by dkapanidis** [comment]
Hi @ptuchik,

The change has been explained in more details in the blog post [here](https://www.kubernetic.com/blog/release-3-3-0):

Summing up the licensing included one-year free updates but was never enforced, you can rollback using the 3.2.0 release to keep using the app if you like and a 20% discount is provided for existing users until 31 of March.

**Comment by ptuchik** [comment]
There was nothing about 1 year free update when I purchased. Thank you. I will move to Lens

**Comment by dkapanidis** [comment]
This was mentioned since [2020](http://web.archive.org/web/20201020134418/https://www.kubernetic.com/):
>  One year of app updates

**Comment by ptuchik** [comment]
It is from October of 2020, I purchased on February 21 of 2020, and there was no word about recurrance
<img width="1154" alt="Screen Shot 2022-02-23 at 1 49 14 AM" src="https://user-images.githubusercontent.com/4479697/155225686-a38f1edd-9caf-4086-91e9-e6db62783941.png">
.

**Comment by ptuchik** [comment]
if I'm not mistaken the version was 0.7.x or something like that. The free and paid version were identical, and I purchased it as a donation for a good work. And here comes the subscription )

**Comment by dkapanidis** [comment]
As mentioned before you can still use the purchased app with the license from Feb 2020.

The licensing change only apply on the renewed development which takes place since `v3.3.0`.

This is a needed step for a more sustainable app development.

**Comment by ptuchik** [comment]
OK!
