### ISSUE TITLE
After upgrading kubernetic asking for License Activation

### ISSUE THREAD

**Issue by dpvmw** [harbur/kubernetic#338]
I have purchased this before and they mentioned it for lifetime, when I purchased initially , Please can you help me on this 

<img width="749" alt="image" src="https://user-images.githubusercontent.com/28822550/155208674-33034223-320d-464d-9930-48f66555ffef.png">

<img width="953" alt="image" src="https://user-images.githubusercontent.com/28822550/155209306-53aaa412-8e2c-4660-8911-87a9516eb432.png">

**Comment by gabrielsyapse** [comment]
same here, i bought the license and i was enduring using it while it's been broken since last year. then the metadata bug was fixed and then another version bump taking away my license.

**Comment by dpvmw** [comment]
@gabrielsyapse so do you know what is the solution for this here?

**Comment by gabrielsyapse** [comment]
I reverted mine by downloading and then clicking to reinstall it (mac os)
```
wget https://kubernetic.s3.amazonaws.com/Kubernetic-3.2.0.dmg
```

**Comment by dkapanidis** [comment]
Hi,

The change has been explained in more details in the blog post [here](https://www.kubernetic.com/blog/release-3-3-0):

Summing up the licensing included one-year free updates but was never enforced, you can rollback using the 3.2.0 release to keep using the app if you like and a 20% discount is provided for existing users until 31 of March.

**Comment by dpvmw** [comment]
@gabrielsyapse thank you 

> I reverted mine by downloading and then clicking to reinstall it (mac os)
> 
> ```
> wget https://kubernetic.s3.amazonaws.com/Kubernetic-3.2.0.dmg
> ```

thank you @gabrielsyapse
