### ISSUE TITLE
[Feature Request] Pinning Namespaces

### ISSUE THREAD

**Issue by ghakobyan-sqsp** [harbur/kubernetic#350]
It would be convenient to pin down selected namespace, so it's possible to scroll via existing contexts and watch the state of namespace with the same name in each context.

**Comment by dkapanidis** [comment]
That's valid point.

Currently when switching context:
* if there is namespace on context it automatically switches to that namespace.
* if there is no namespace on context it automatically switches to `default` namespace.

One way to cover this would be to change the functionality when no namespace is configured on a context to not switch to `default`, so if you wanted to *pin* the namespace you would simply use contexts without namespaces.

For those that want the old functionality they would configure their context with `default` namespace to automatically switch there.

Would that work for your use-case?

An alternative would be to enable/disable the auto-switch of namespace on preferences.

**Comment by ghakobyan-sqsp** [comment]
Yes, either of these will solve the problem.

**Comment by dkapanidis** [comment]
Done in `4.3.0`

Namespace on dropdown can now be pinned and it will be unchanged when switching contexts.

![2022-07-11 16 36 57](https://user-images.githubusercontent.com/367397/178289714-c2524baf-4833-4f69-b6b2-6a1bca7ce789.gif)
