### ISSUE TITLE
license key not accepted by newest kubernetic version

### ISSUE THREAD

**Issue by dflottmann** [harbur/kubernetic#351]
Hello,

I ordered a new kubernetic license on the 28.02.2022.
If I enter this license key in the activation dialogue of kubernetic 4.0.1, I am not able to activate my license. The 'Activate' Button remains greyed out.

**Comment by dkapanidis** [comment]
Hi @dflottmann,

I just tested your license code and it works ok for 4.0.1.

Some common issues with the license code are the following:
- Keys are finished with two `==` characters, make sure when copying the text they are also included.
- Some mail clients have been reported to split license keys with end-of-line. Make sure there are no empty lines between characters.
- In a weird situation a mail client added a "!" character in the license keys. The license keys are b64 of the signed license. They do not include characters such as "!". You can test by doing `echo $LICENSE_KEY  | base64 -D`.

Please confirm if that works for you.

**Comment by dflottmann** [comment]
Hello Dimitris,

the `==` at the end of the license key did the trick. It did not get copied over when extracting the key from the mail.
Unfortunately this was hard to check, since the license key was not fully rendered in the mail I received. Please see below.

I would have had to inspect the raw content of the mail to find this flaw... and even then the license key was modified by line breaks in the sources.

Anyhow, it works now. :) 
Thx

<img width="1063" alt="Screenshot 2022-04-19 at 20 46 40" src="https://user-images.githubusercontent.com/35294991/164075234-a1cb09df-a1f6-4684-8ea8-0b44f71dff91.png">
