### ISSUE TITLE
Add context menu (right-click menu) on resources

### ISSUE THREAD

**Issue by dkapanidis** [harbur/kubernetic#355]
Added context menu with right-click on the resources. This replaces the buttons on the right side of each row.

![2022-05-16 12 11 45](https://user-images.githubusercontent.com/367397/168603732-433bfc8f-b1a6-4f80-8dde-1f76e244bad2.gif)

**Comment by mrjamiebowman** [comment]
I think we are going the right direction here. However I have some suggestions.

* I liked the arrows "<" and ">" on deployments for scaling up deployments that was there before. I don't think that should have been removed. It's a lot easier to scale down rapidly by clicking those than using the context menu.

* now the context menu was a GREAT addition .. but imagine we have 100 pods running and want to scale down to 0? It would be beneficial if there was a "Scale To" option where I could specify the number of pods that I want to scale to. Right clicking, scale down to get to 0 from a higher number is difficult.
