### ISSUE TITLE
Kubernetic v4.1.0 -- unable to resize the application (running on windows)

### ISSUE THREAD

**Issue by billpieper** [harbur/kubernetic#357]
Prior to updating to v4.1.0, I was able to resize the application without issue.

Post upgrade, resizing does not seem to work or be allowed...

**Comment by dkapanidis** [comment]
Hi, what is your OS?

**Comment by dkapanidis** [comment]
I'm on it

**Comment by dkapanidis** [comment]
Done, new update is published for win (4.1.1). Starting your app will ask for update.

If you can confirm this fixes it from your side would be great. I'll update the landing page download link.

**Comment by dkapanidis** [comment]
Fixed on `4.1.1` (released only for Win).

closing (if the issue persists, please reopen and comment)
