### ISSUE TITLE
4.1.0 & 4.1.1 - Options like delete or edit are gone

### ISSUE THREAD

**Issue by Sonorpearl** [harbur/kubernetic#358]
Hello,

under Windows options like delete or edit are gone. You can't delete/edit/update a job/deployment anymore, the buttons are just missing. It's missing everywhere.

**Comment by dkapanidis** [comment]
Check the release [post](https://www.kubernetic.com/blog/release-4-1-0) for more details. The buttons are under a context menu by right clicking on the row.

![image](https://user-images.githubusercontent.com/367397/168792000-a8770790-d434-4b1f-a8b4-a722f2d5e602.png)
