### ISSUE TITLE
Kubernetic using deprecated APIs

### ISSUE THREAD

**Issue by edh31** [harbur/kubernetic#362]
I have noticed that Kubernetic v4.1.0 is using deprecated APIs (https://kubernetes.io/docs/reference/using-api/deprecation-guide/)

In a lot of my clusters I see the following warnings on Kubernetic logs:

```
W0616 09:51:09.401715   12608 warnings.go:67] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

W0616 09:51:09.056790   12608 warnings.go:67] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

The usage of extensions/v1beta1 Ingress is causing that GKE prompts the following warning:

![image](https://user-images.githubusercontent.com/43973471/174099554-74489fc2-9ed7-43f5-ae11-fa34351215b3.png)

**Comment by dkapanidis** [comment]
Fixed for next release (4.3.0)

All references to `betav1` APIs have been upgraded to stable v1 versions. More specifically the following changes are applied:

* ingresses from `extensions/v1beta1` to `networking/v1`
* cronjobs from `batch/v1beta1` to `batch/v1`
