### ISSUE TITLE
Context Menu on Logs

### ISSUE THREAD

**Issue by mrjamiebowman** [harbur/kubernetic#364]
Would be useful if when viewing the logs we could right-click "Copy" on a selection.. or "Select All" or "Save" as a text file.. 

if I highlight something.. I don't have the ability to right-click copy. I can CTRL + C but can't right-click copy.

**Comment by dkapanidis** [comment]
Done, will be available on 4.3.0

![2022-06-30 10 38 34](https://user-images.githubusercontent.com/367397/176632706-2806ef94-c5cf-440f-87ab-4c6c42c92dae.gif)

**Comment by mrjamiebowman** [comment]
That looks amazing!
