### ISSUE TITLE
[Bug] Pinned Resources extends to preferences/context/etc

### ISSUE THREAD

**Issue by pinkfloydx33** [harbur/kubernetic#367]
#304 Added Pinned Resource Types. It appears this extends to all top-level screen in the application, i.e. you can pin "preferences", "contexts", "port forwards", etc. However pinning these adds a "blank" item to the Favorites list that is then shared for all of them (pinning contexts *and* preferences only adds one item). Clicking this blank item navigates you to a blank page

Note: I don't need nor want the ability to pin these additional screens. I was just trying out the new feature and stumbled upon the bug.

**Comment by dkapanidis** [comment]
good catch, this is now fixed for next release
