### ISSUE TITLE
Use clusterize.js for better handling of large lists

### ISSUE THREAD

**Issue by genevera** [harbur/kubernetic#37]
When viewing Events or any other large list, the application eats up a ton of memory and becomes unusable.  Something like https://clusterize.js.org/ would be a good idea her since it could reduce the memory footprint.

**Comment by spiddy** [comment]
Sound's interesting as an option. There is also the possibility to add pagination or inifinite-scrolling option to reduce memory footprint.

**Comment by spiddy** [comment]
Added pagination to support too many items on same screen, this can be closed now
