### ISSUE TITLE
Expired licence?

### ISSUE THREAD

**Issue by AlexandreCassagne** [harbur/kubernetic#373]
I bought a Kubernetic Desktop (perpetual) licence in 2020 but it seems like you have expired it. Why did it expire? Can you please issue me with a code that will work?

**Comment by cazter** [comment]
We are also unable to activate our licenses. I also tried getting a new evaluation license and that too failed to activate.

**Comment by bollicino** [comment]
@AlexandreCassagne look at this [blog post](https://www.kubernetic.com/blog/release-3-3-0)
also, IMHO, the project seems to be dead.

**Comment by dkapanidis** [comment]
Thanks @bollicino for the blog post link. I have explained [here](https://github.com/harbur/kubernetic/issues/363#issuecomment-1175972838) in detail.

@cazter the evaluation license is for the Team version deployed as a chart, not the desktop edition, licenses are different.

The project is not dead btw, any feature requests are welcome.
