### ISSUE TITLE
getting credentials: exec: executable gke-gcloud-auth-plugin not found

### ISSUE THREAD

**Issue by lavjain** [harbur/kubernetic#377]
The plugin is already installed inside google-cloud-sdk/bin directory and kubectl commands work properly from command line

**Comment by akashagarwal7** [comment]
+1, same issue.

**Comment by akashagarwal7** [comment]
+1, same issue. @lavjain were you able to resolve this?

**Comment by akashagarwal7** [comment]
On my mac, I had to modify the correct `user.exec` in my `~/.kube/config` to change the `command` from `gke-gcloud-auth-plugin` to this:
```
command: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gke-gcloud-auth-plugin
provideClusterInfo: true # This needs to be added as well.
```

The path could be different.
