### ISSUE TITLE
Javascript error in the main process

### ISSUE THREAD

**Issue by cabrinoob** [harbur/kubernetic#38]
Hi,
I have upgraded to the the last version 2.0.10. And now, I have an error message at startup : 

![error](https://i.imgur.com/OoU0uZJ.png)

I was using a previous version where everything worked fine. I did not change my kubeconfig.
I have 3 clusters in it (one with RBAC mode activated) and each one was working fine with the previous version.

Thank you.

**Comment by spiddy** [comment]
Hi,

do you know what was the previous version that you were using?

**Comment by spiddy** [comment]
The error is obscured by a try/catch that is now removed. I've release an upgrade (v2.0.11) that will help identify better the error.

Can you upgrade (Menu > Kubernetic > Check for Update) and report the full error?

Also, what OS are you working with?

**Comment by cabrinoob** [comment]
@spiddy : Hi,
Thank you for your quick response. I'am using the windows version and I don't remember the old version I was using (perhaps 1.8.xx).

I have installed the new one (2.0.11) and the message version is clearer. It seems that kubernetic cannot get the current user to locate the kubeconfig file :

![image](https://i.imgur.com/PxSlvZh.png)

Note the "undefined" in the path.

Hope it help to fix the problem.

Thank you

**Comment by spiddy** [comment]
Ok, try to update to 2.0.12 it should be fixed now.

**Comment by cabrinoob** [comment]
Great!! It works now. Thank you for your help!
