### ISSUE TITLE
Bought a license and License Code does not activate the App

### ISSUE THREAD

**Issue by jp15310** [harbur/kubernetic#380]
I paid for a license and I cannot activate the app.  I followed the instructions as described in the email containing the license code:

- Copy and paste the code to the application preferences tab to get your app activated.

![Screenshot 2023-06-28 at 10 25 37 AM](https://github.com/harbur/kubernetic/assets/8593417/d3e8a773-eed1-4ca4-82ea-bdac05834ab0)

**Comment by dkapanidis** [comment]
There are two more characters on the license: add to the end "==" and that should work ok.

The problem is when copying the text it doesn't normally doesn't add those two characters when selecting the text.

Let me know if this fixes your problem

**Comment by jp15310** [comment]
Gracias - it worked.  The email only shows the license in a single line, so I cannot see the whole license.
