### ISSUE TITLE
Kubernetic-Desktop Activation not possible

### ISSUE THREAD

**Issue by Kryjom** [harbur/kubernetic#387]
Hi,
Hi I need some support. I pasted in my Email and my Activation Code Date but the Activate-Button is not getting green. In consequence activation is not executed. 

Regards
JK

**Comment by dkapanidis** [comment]
hi,

the activation code finishes with “==“. make sure you include that as well when you enter the activation code.

more specifically your activation code finishes in kifQ==

**Comment by Kryjom** [comment]
My activation code looks quite good - eyJsaWNlbnNlIjp7ImRhdGUiOiIwNi0wNy0yMDI0ID . . . M1NzE3MTkifQ==
