### ISSUE TITLE
[Feature] Terminal for pod

### ISSUE THREAD

**Issue by micdah** [harbur/kubernetic#45]
Adding option to open a terminal, when viewing a pod.

**Comment by vivekskrishna** [comment]
+1

**Comment by s1rc** [comment]
@dkapanidis Is there an ETA for this feature on your roadmap?

**Comment by dkapanidis** [comment]
This is planned for next release, so soon hopefully.

**Comment by dkapanidis** [comment]
Added support for Terminal on Pods (v2.6.0)

Terminal is available on Pods and it opens on first container inside the pod and runs shell `sh`. 

Future versions will support selecting container, Terminal on controllers and services (choosing underlying pods of service on UI), trying dynamically different potential shells, or [debugging with an ephemeral pod](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container).

![2020-04-13 17-53-46 2020-04-13 17_56_33](https://user-images.githubusercontent.com/367397/79135863-4e530080-7db0-11ea-8c7c-8451ea49936c.gif)
