### ISSUE TITLE
[Feature] StatefulSet resources

### ISSUE THREAD

**Issue by cabrinoob** [harbur/kubernetic#49]
Hi,
I love kubernetic, but in the v2.0.14 I did not find how to display Statefulset resources. Do you plan to add this feature?

**Comment by jnaidoo-git** [comment]
Hi
I use kubernetic on a daily basis and I also find the lack of being able to display statefulset resources problematic. Please can we have a response on this?

**Comment by spiddy** [comment]
StatefulSets are now supported since v2.0.15 (Pending to be released)
