### ISSUE TITLE
Please reconsider the "full screen window on launch" startup behavior

### ISSUE THREAD

**Issue by nugget** [harbur/kubernetic#52]
Please reconsider your decision to make the Kubernetic window expand to fill the entire available display size on launch.  This is very un-neighborly behavior for an application and for users with large displays it can be comically unusable.

**Comment by spiddy** [comment]
ok, that makes sense, it was changed because it's original size was too small, but you're right full-screen is an overkill for some situations.

**Comment by spiddy** [comment]
Window is now reverted to non-fullscreen format.
