### ISSUE TITLE
Could not start kubernetic on Win10

### ISSUE THREAD

**Issue by vasili439** [harbur/kubernetic#58]
Hi! Could not start kubernetic 2.0.15 on Win10 Pro (Version 1803, OS build 17134.112) with the following error:
![image](https://user-images.githubusercontent.com/23239384/42432103-a076e6e8-8351-11e8-8805-ddbd1e140178.png)

**Comment by a1ii54** [comment]
I am facing a similar issue after upgrading
![image](https://user-images.githubusercontent.com/25863579/42555885-0c467f2a-84ea-11e8-9618-adec997baf0e.png)

**Comment by spiddy** [comment]
fixed

**Comment by vasili439** [comment]
@spiddy , Thank you! Just tested and it works fine
