### ISSUE TITLE
2.0.15 error at installation

### ISSUE THREAD

**Issue by cabrinoob** [harbur/kubernetic#60]
Hi,
I've just downloaded the 2.0.15 to upgrade from my 2.0.14 and I have this error message at lauch time : 

![error](https://i.imgur.com/kkHopED.png)

I'am under Windows 10

**Comment by spiddy** [comment]
The issue is resolved at [2.0.16](https://docs.kubernetic.com/changelog)

The version is released 2.0.16 but the website with the link is not updated yet, try the direct link: https://kubernetic.s3.amazonaws.com/Kubernetic+Setup+2.0.16.exe

I'll update the website to reflect the new version

**Comment by cabrinoob** [comment]
Thank you!

**Comment by spiddy** [comment]
site updated
