### ISSUE TITLE
Blank page when tiller is not installed

### ISSUE THREAD

**Issue by shaicoleman** [harbur/kubernetic#61]
When clicking on "Charts" on the sidebar, if tiller isn't installed a blank page is shown.
For better user experience, and error message should be displayed instead.

In the console the following message is shown
```
(node:30850) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 29): Error: Command failed: /usr/local/bin/helm list --namespace default
Error: could not find tiller
```

**Comment by spiddy** [comment]
Fixed, will be on next release.

Now it checks properly for Tiller existence and provides a click-me button to deploy with some sane defaults. For customization you can refer to Helm documentation.

<img width="995" alt="screen shot 2018-07-28 at 11 26 40" src="https://user-images.githubusercontent.com/367397/43355229-418a5bd0-9259-11e8-8ab8-a3e4c9ae0365.png">
