### ISSUE TITLE
Win10: Wrong pod's age

### ISSUE THREAD

**Issue by vasili439** [harbur/kubernetic#67]
Hi! Version 2.1.0. For newly created pods I see "AGE: 57 minutes from now" but actual pod's age is up to 3 minutes.

**Comment by spiddy** [comment]
Hi!

I can't seem to be able to reproduce this, fresh new Pods appear with correct age.

Is this problem consistent? Can you reproduce it or is it a one-time only?
Was this working ok on the same machine before v2.1.0?
If you create a fresh Pod (You can now use the `Create` button) does the same problem appear?
Lastly if you do `kubectl get pod` does the Pod age appear correctly? There may be time difference between your server and you.

Can you add a screenshot here?

**Comment by vasili439** [comment]
Sorry.  Looks like it was once and now I cannot reproduce it anymore.
