### ISSUE TITLE
Stuck on new download update ?

### ISSUE THREAD

**Issue by gaelleiadvize** [harbur/kubernetic#70]
Hi 

Kubernetic seems to be stuck on downloading new update (I'm currently in 2.1.0)

<img width="431" alt="capture d ecran 2018-10-22 14 18 19" src="https://user-images.githubusercontent.com/6837504/47292327-e8e0e200-d606-11e8-856e-902d87a36fa2.png">

I click on "Sure", the app asks me to restart but I see again the first message.

If a go to "Check for Update" I see this : 
<img width="446" alt="capture d ecran 2018-10-22 14 33 27" src="https://user-images.githubusercontent.com/6837504/47292534-9bb14000-d607-11e8-9a3d-c68a27b196c5.png">

Is there an available update or is it an issue ? 
Cause when a go to the website the last version is 2.1.0 too

Info : 
 OSX Hight Sierra (v 10.13.6)

Thx 😃 

Edit : Is there a link with the current Github issue ?

**Comment by spiddy** [comment]
I've tried to reproduce your error, it works fine for me: (Download Kubernetic 2.1.0, start, run update, restart, check version is 2.2.0)

Environment is also OSX High Sierra v10.13.6.

Can you try again? maybe internet had it's issues, (maybe related with with github downtime?)
Binaries are distributed through an AWS S3 bucket by the way, so github shouldn't be an issue here.

**Comment by spiddy** [comment]
btw, landing page should be updated soon pointing to 2.2.0 version.
