### ISSUE TITLE
[Feature] Change Font Size

### ISSUE THREAD

**Issue by gmr** [harbur/kubernetic#76]
Love the app but the font size is way small on my screen. Would love to be able to increase the default font-size for the app so I can read the labels without straining (or glasses). I've included a screenshot so you can see the relative size difference between default (and personally set) sizes of a couple different apps for context.

![screen shot 2018-12-31 at 3 05 48 pm](https://user-images.githubusercontent.com/49469/50566984-ad9d1680-0d0d-11e9-8458-55e0f17e1790.png)

**Comment by webberwang** [comment]
Yeah the font is quite small, a zoom + option would be a life saver

**Comment by dkapanidis** [comment]
added zoom-in & out options ref #273
