### ISSUE TITLE
[Feature] Refresh button and refresh rate option for current page

### ISSUE THREAD

**Issue by cazzoo** [harbur/kubernetic#78]
Currently there no other way to refresh page than clicking on another page and getting back to current page.
This could be annoying when looking for pod status changes.
Also, it'd be nice to have ability to have autorefresh rate on every pages.

**Comment by dkapanidis** [comment]
added refresh button on topmenu
will be released on 2.8.0

![refresh](https://user-images.githubusercontent.com/367397/82543347-b1744780-9b53-11ea-9cb8-67b86357b844.gif)

pages are loading items in watch mode and are refreshing live when changes are applied, the refresh button is there only for cases where the connectivity socket is broken for some reason (e.g. networking issues).
