### ISSUE TITLE
Display CRD's

### ISSUE THREAD

**Issue by kmadnani** [harbur/kubernetic#81]

**Comment by vivekskrishna** [comment]
+1 , this will be helpful for seeing all CRD's created in a service mesh for example using Istio.

**Comment by alexeldeib** [comment]
+1, it's doable via discovery. https://godoc.org/k8s.io/client-go/discovery#DiscoveryClient.ServerGroupsAndResources probably

**Comment by dkapanidis** [comment]
CRDs are available on 2.7.0:

<img width="1272" alt="Screenshot 2020-05-19 at 12 22 49" src="https://user-images.githubusercontent.com/367397/82315371-7e06b100-99cb-11ea-827f-0f940b540cc7.png">

Note that at the moment only namespaced CRDs are visible, on next release the global CRDs will also be available.
