### ISSUE TITLE
Chart deployment not working

### ISSUE THREAD

**Issue by byrner75** [harbur/kubernetic#84]
Version 2.2.0

When I try install a chart I just get a spinner in the Values pane of the screen.

I also see the following in the log file (not sure if its related)
[2019-02-27 19:28:43.884] [error] Error: spawn helm ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

The following is the output from helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

**Comment by byrner75** [comment]
Seems to be an issue with helm as I cannot see releases either.

**Comment by spiddy** [comment]
ENOENT translates to file not found. Is helm installed in your system PATH?

**Comment by byrner75** [comment]
Yeah, I can call helm from the terminal. I've just noticed if I launch Kubernetic from the terminal it works !! So wondering if helm is on the path for apps launched from dock.

**Comment by byrner75** [comment]
This sorted it for me.
launchctl setenv PATH /usr/local/bin:$(launchctl getenv PATH)
