### ISSUE TITLE
Nothing loads on AKS cluster 

### ISSUE THREAD

**Issue by andrebriggs** [harbur/kubernetic#85]
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/3119513/53824706-9d6a1780-3f9a-11e9-816d-4a6102d68e23.png">

Running Mac OS 10.14.2 and k8s v1.11.6 with RBAC.

Too bad this isn't open source. What a waste

**Comment by TraGicCode** [comment]
Same here running into the same issue

**Comment by dstrimble** [comment]
I have the same issue. Works on other clusters but not AKS clusters.

**Comment by durch** [comment]
+1 here

**Comment by GranularSystems** [comment]
+1 here

**Comment by andrea-zoleo** [comment]
The Kubernetic is run as an App in OSX so it doesn't have access to a fully configured PATH env variable.
Try putting the absolute path to the aws-iam-authenticator in the ~/.kube/config file

**Comment by spiddy** [comment]
🎆 EKS clusters are now supported by Kubernetic since 2.3.0 📦 version.

absolute path is necessary in OSX as commented by @andrea-zoleo so that Kubernetic can locate the `aws-iam-authenticator`.
