### ISSUE TITLE
Steps to install Kubernetic on Linux CentOS

### ISSUE THREAD

**Issue by vivekskrishna** [harbur/kubernetic#87]
Hi,
  I was going through the documentation and i couldnt find the info to steps to install it correctly in a Linux environment. If a Page witht the required packages can eb updated, it would be helpful for users to install it and use it easily.

**Comment by vivekskrishna** [comment]
i was able to manually find the packages and intall it. since it may vary depending on the flavour  i am closing this but feel free to contact me if any info is needed.

**Comment by spiddy** [comment]
Hi can you clarify what packages are installed manually?

The Kubernetic installer is a `tar.gz` file that should be extracted, it contains the `kubernetic` executable that can be run to start the application.

I'm not actively using Linux to run it so if there is a specific package missing or required we can add the info on the [installation page](https://docs.kubernetic.com/installation)

**Comment by vivekskrishna** [comment]
I just noticed my linux needed following packages for kubernetic to run
 yum install pango.x86_64
 yum install libXcomposite.x86_64
 yum install gdk-pixbuf2.x86_64
 yum install atk.x86_64
 yum install GConf2.x86_64
 yum install libNX_X11.x86_64
 yum install cups.x86_64
 yum install gtk2
 yum install libXScrnSaver
 yum install pango-devel.x86_64

**Comment by florimm** [comment]
How about Ubuntu?

**Comment by vivekskrishna** [comment]
Haven’t tried it in Ubuntu.sorry
