### ISSUE TITLE
Weird results with multiple contexts

### ISSUE THREAD

**Issue by roynasser** [harbur/kubernetic#92]
I've been trying out kubernetic, and when using multiple clusters, all defined in a kubeconfig file I'm getting very strange behavior...

It seem for some reason kubernetic is showing all of my contexts together...

Check this print for reference:
![image](https://user-images.githubusercontent.com/1218902/55573008-42cdf380-56df-11e9-9066-bef0bcd4df13.png)
(On the left is the correct output from kubectl)

Switching contexts in kubernetic doesnt help... it just begins listing all of the resources from all the contexts.  I do see the "current-context" being set in the kubeconfig file, but it doesnt seem to make much of a difference?

EDIT: I noticed that this happens after accessing a different context.  It seems the contexts are "cached"... Dont know what causes this, or if this makes any sense... I think this wasnt happening before :/ but I wasnt paying attention closely... (Also since we only see the first 25 hosts in the list its very difficult to notice in normal non-dev clusters)... can we increease this or have an unlimited/all view?

**Comment by alex-hempel** [comment]
I am experiencing the same issue, it seems to manifest when I switch back and forth between contexts.

**Comment by dkapanidis** [comment]
This issue is fixed now
