### ISSUE TITLE
[FEATURE REQUEST] Support HTTP Proxies

### ISSUE THREAD

**Issue by teancom** [harbur/kubernetic#93]
I am behind a corporate firewall, attempting to connect to a cluster hosted in AWS. All HTTP/S communication must go through our corporate proxy. Command-line utilities generally read `HTTP_PROXY` (or variants), which is fine. GUI tools often support the system-wide HTTP proxy setting in the OSX System Preferences -> Network -> Advanced -> Proxies tab. Kubernetic, afaict, does neither.

**Comment by wutkemtt** [comment]
We need this feature too. While weare using kubectl to connect to several clusters in Azure we need to use a special local proxy to overcome our corporate proxy. Therefore we need a configuration or environment option.

**Comment by dkapanidis** [comment]
Added on Kubernetic release v2.5.0

Now on Preferences tab you can configure your usual proxy variables (HTTP_PROXY, HTTPS_PROXY, NO_PROXY) which will be used for connectivity to the kubernetes clusters.

If you have combination of proxy and no proxy clusters you can use the NO_PROXY variable to exclude the hosts of the ones that should not use the proxy.

Please note that you must restart Kubernetic for proxy configuration to be taken into account.

<img width="825" alt="Screenshot 2020-02-22 at 18 36 01" src="https://user-images.githubusercontent.com/367397/75096717-991b7d80-55a2-11ea-93ca-f394b1d0c19b.png">
