### ISSUE TITLE
support cronjob

### ISSUE THREAD

**Issue by zhaoyao91** [harbur/kubernetic#94]
How about support cronjob?

**Comment by dkapanidis** [comment]
Added support for cronjobs (v2.6.0)

<img width="827" alt="Screenshot 2020-04-13 at 17 18 41" src="https://user-images.githubusercontent.com/367397/79132587-e5b55500-7daa-11ea-96da-dbe96e2d462d.png">

<img width="819" alt="Screenshot 2020-04-13 at 17 19 19" src="https://user-images.githubusercontent.com/367397/79132605-eea62680-7daa-11ea-8fe7-49e4b98515d5.png">
