### ISSUE TITLE
RBAC editing

### ISSUE THREAD

**Issue by yverbin** [harbur/kubernetic#95]
Have any any plans to implement RBAC editing ?

**Comment by dkapanidis** [comment]
will be released on v2.7.0

**Comment by dkapanidis** [comment]
Now Role, RoleBindings, ClusterRole & ClusterRoleBindings can be managed through Kubernetic under the User Management section:

<img width="1103" alt="Screenshot 2020-05-11 at 09 38 15" src="https://user-images.githubusercontent.com/367397/81536043-2c2aaf00-936b-11ea-8db8-c6d8d7fea2d6.png">
