### ISSUE TITLE
Logs should auto scroll

### ISSUE THREAD

**Issue by mustakimali** [harbur/kubernetic#99]
The Logs viewer for Pods should auto scroll as new logs appears.

**Comment by yakcamnevets** [comment]
+1 this would be a great feature!

**Comment by kavishdahekar** [comment]
Has this been implemented?

**Comment by dkapanidis** [comment]
not yet, though it is in the backlog for future releases

**Comment by dkapanidis** [comment]
done on 2.8.0, pending for release:

Scroll to bottom flag (enabled by default) will automatically scroll to bottom on new entries.

![autoscroll](https://user-images.githubusercontent.com/367397/82420085-8ae4dc80-9a7f-11ea-9d41-8d246021ed4f.gif)
